local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
	local sym = injected_functions.sym
	return {
		SpecialKey({ fg = "#545c7e" }),
		EndOfBuffer({ fg = "#222436" }),
		TermCursor({ gui = "reverse" }),
		GitSignsAddInline({ TermCursor }),
		GitSignsDeleteInline({ TermCursor }),
		GitSignsChangeInline({ TermCursor }),
		NonText({ fg = "#545c7e" }),
		GitSignsCurrentLineBlame({ NonText }),
		TelescopePromptCounter({ NonText }),
		TelescopeResultsDiffUntracked({ NonText }),
		TelescopePreviewHyphen({ NonText }),
		Directory({ fg = "#82aaff" }),
		TelescopePreviewDirectory({ Directory }),
		TelescopePreviewDate({ Directory }),
		MiniPickIconDirectory({ Directory }),
		LspKindFolder({ Directory }),
		MiniFilesDirectory({ Directory }),
		OilDir({ Directory }),
		ErrorMsg({ fg = "#c53b53" }),
		NvimInvalidSpacing({ ErrorMsg }),
		IncSearch({ bg = "#ff966c", fg = "#1b1d2b" }),
		CurSearch({ IncSearch }),
		MiniOperatorsExchangeFrom({ IncSearch }),
		MiniPickPreviewRegion({ IncSearch }),
		Search({ bg = "#3e68d7", fg = "#c8d3f5" }),
		TelescopePreviewMatch({ Search }),
		MoreMsg({ fg = "#82aaff" }),
		ModeMsg({ fg = "#828bb8", gui = "bold" }),
		LineNr({ fg = "#3b4261" }),
		TelescopeResultsLineNr({ LineNr }),
		LineNrAbove({ fg = "#017dc5" }),
		LineNrBelow({ fg = "#017dc5" }),
		CursorLineNr({ fg = "#ff966c", gui = "bold" }),
		Question({ fg = "#82aaff" }),
		StatusLine({ bg = "#1e2030", fg = "#828bb8" }),
		MsgSeparator({ StatusLine }),
		WinBar({ StatusLine }),
		StatusLineTerm({ StatusLine }),
		StatusLineNC({ bg = "#1e2030", fg = "#3b4261" }),
		WinBarNC({ StatusLineNC }),
		StatusLineTermNC({ StatusLineNC }),
		WinSeparator({ fg = "#1b1d2b", gui = "bold" }),
		VertSplit({ fg = "#1b1d2b" }),
		Title({ fg = "#82aaff", gui = "bold" }),
		sym("@markup.heading")({ Title }),
		MiniDepsTitle({ Title }),
		MiniMapSymbolLine({ Title }),
		Visual({ bg = "#2d3f76" }),
		SnippetTabstop({ Visual }),
		TelescopePreviewLine({ Visual }),
		MiniPickMatchMarked({ Visual }),
		BlinkCmpDocCursorLine({ Visual }),
		WarningMsg({ fg = "#ffc777" }),
		WildMenu({ bg = "#2d3f76" }),
		Folded({ bg = "#3b4261", fg = "#82aaff" }),
		FoldColumn({ fg = "#636da6" }),
		CursorLineFold({ FoldColumn }),
		DiffAdd({ bg = "#273849" }),
		sym("@diff.plus")({ DiffAdd }),
		GitSignsAddLn({ DiffAdd }),
		GitSignsAddPreview({ DiffAdd }),
		TelescopeResultsDiffAdd({ DiffAdd }),
		MiniDiffOverAdd({ DiffAdd }),
		DiffChange({ bg = "#252a3f" }),
		sym("@diff.delta")({ DiffChange }),
		GitSignsChangeLn({ DiffChange }),
		TelescopeResultsDiffChange({ DiffChange }),
		MiniDiffOverContext({ DiffChange }),
		DiffDelete({ bg = "#3a273a" }),
		sym("@diff.minus")({ DiffDelete }),
		GitSignsDeletePreview({ DiffDelete }),
		GitSignsDeleteVirtLn({ DiffDelete }),
		TelescopeResultsDiffDelete({ DiffDelete }),
		MiniDiffOverDelete({ DiffDelete }),
		DiffText({ bg = "#394b70" }),
		MiniDiffOverChange({ DiffText }),
		SignColumn({ fg = "#3b4261" }),
		CursorLineSign({ SignColumn }),
		Conceal({ fg = "#737aa2" }),
		LspKindSnippet({ Conceal }),
		SpellBad({ sp = "#c53b53", gui = "undercurl" }),
		SpellCap({ sp = "#ffc777", gui = "undercurl" }),
		SpellRare({ sp = "#4fd6be", gui = "undercurl" }),
		SpellLocal({ sp = "#0db9d7", gui = "undercurl" }),
		Pmenu({ bg = "#1e2030", fg = "#c8d3f5" }),
		PmenuKind({ Pmenu }),
		PmenuExtra({ Pmenu }),
		PmenuSel({ bg = "#363c58" }),
		PmenuKindSel({ PmenuSel }),
		PmenuExtraSel({ PmenuSel }),
		BlinkCmpMenuSelection({ PmenuSel }),
		PmenuMatch({ bg = "#1e2030", fg = "#65bcff" }),
		PmenuMatchSel({ bg = "#363c58", fg = "#65bcff" }),
		PmenuSbar({ bg = "#27293a" }),
		BlinkCmpScrollBarGutter({ PmenuSbar }),
		PmenuThumb({ bg = "#3b4261" }),
		BlinkCmpScrollBarThumb({ PmenuThumb }),
		TabLine({ bg = "#1e2030", fg = "#3b4261" }),
		TabLineSel({ bg = "#82aaff", fg = "#1b1d2b" }),
		TabLineFill({ bg = "#1b1d2b" }),
		CursorColumn({ bg = "#2f334d" }),
		CursorLine({ bg = "#2f334d" }),
		MiniPickMatchCurrent({ CursorLine }),
		MiniPickPreviewLine({ CursorLine }),
		MiniFilesCursorLine({ CursorLine }),
		ColorColumn({ bg = "#1b1d2b" }),
		QuickFixLine({ bg = "#2d3f76", gui = "bold" }),
		Whitespace({ fg = "#3b4261" }),
		NormalNC({ fg = "#c8d3f5" }),
		NormalFloat({ bg = "#0f0f14", fg = "#a0c0d0" }),
		MiniFilesNormal({ NormalFloat }),
		MiniPickNormal({ NormalFloat }),
		MiniMapNormal({ NormalFloat }),
		MiniClueDescSingle({ NormalFloat }),
		MiniNotifyNormal({ NormalFloat }),
		MiniAnimateNormalFloat({ NormalFloat }),
		BlinkCmpDocSeparator({ NormalFloat }),
		MsgArea({ fg = "#828bb8" }),
		FloatBorder({ bg = "#0f0f14", fg = "#0f0f14" }),
		MiniFilesBorder({ FloatBorder }),
		MiniClueBorder({ FloatBorder }),
		MiniPickBorder({ FloatBorder }),
		MiniNotifyBorder({ FloatBorder }),
		WhichKeyBorder({ FloatBorder }),
		Cursor({ bg = "#c8d3f5", fg = "#222436" }),
		FloatTitle({ bg = "#1e2030", fg = "#589ed7" }),
		FloatFooter({ FloatTitle }),
		MiniClueTitle({ FloatTitle }),
		MiniNotifyTitle({ FloatTitle }),
		MiniFilesTitle({ FloatTitle }),
		WhichKeyTitle({ FloatTitle }),
		RedrawDebugNormal({ gui = "reverse" }),
		Underlined({ gui = "underline" }),
		sym("@string.special.url")({ Underlined }),
		sym("@markup.link.url")({ Underlined }),
		lCursor({ bg = "#c8d3f5", fg = "#222436" }),
		CursorIM({ bg = "#c8d3f5", fg = "#222436" }),
		Substitute({ bg = "#ff757f", fg = "#1b1d2b" }),
		VisualNOS({ bg = "#2d3f76" }),
		Normal({ fg = "#c8d3f5" }),
		Ignore({ Normal }),
		NvimSpacing({ Normal }),
		LspKindFile({ Normal }),
		Character({ fg = "#c3e88d" }),
		sym("@character")({ Character }),
		Constant({ fg = "#ff966c" }),
		Number({ Constant }),
		Boolean({ Constant }),
		sym("@constant")({ Constant }),
		TelescopePreviewCharDev({ Constant }),
		TelescopePreviewPipe({ Constant }),
		TelescopeResultsConstant({ Constant }),
		TelescopePreviewGroup({ Constant }),
		TelescopePreviewUser({ Constant }),
		TelescopePreviewRead({ Constant }),
		TelescopePreviewBlock({ Constant }),
		luaConstant({ Constant }),
		Statement({ fg = "#c099ff" }),
		Conditional({ Statement }),
		Repeat({ Statement }),
		Label({ Statement }),
		Exception({ Statement }),
		TelescopePreviewWrite({ Statement }),
		TelescopePreviewSocket({ Statement }),
		luaStatement({ Statement }),
		Keyword({ fg = "#86e1fc" }),
		TelescopePreviewSticky({ Keyword }),
		OilSocket({ Keyword }),
		PreProc({ fg = "#86e1fc" }),
		Include({ PreProc }),
		Define({ PreProc }),
		Macro({ PreProc }),
		PreCondit({ PreProc }),
		sym("@attribute")({ PreProc }),
		sym("@keyword.directive")({ PreProc }),
		sym("@annotation")({ PreProc }),
		Type({ fg = "#65bcff" }),
		StorageClass({ Type }),
		Structure({ Type }),
		Typedef({ Type }),
		sym("@type")({ Type }),
		NvimNumberPrefix({ Type }),
		NvimOptionSigil({ Type }),
		TelescopeMultiSelection({ Type }),
		sym("@markup.environment.name")({ Type }),
		Special({ fg = "#65bcff" }),
		Tag({ Special }),
		SpecialChar({ Special }),
		SpecialComment({ Special }),
		sym("@constant.builtin")({ Special }),
		sym("@attribute.builtin")({ Special }),
		sym("@function.builtin")({ Special }),
		Delimiter({ Special }),
		sym("@tag.builtin")({ Special }),
		TelescopePreviewLink({ Special }),
		LspKindEvent({ Special }),
		MiniMapSymbolCount({ Special }),
		LspKindColor({ Special }),
		sym("@markup.math")({ Special }),
		OilChange({ Special }),
		Debug({ fg = "#ff966c" }),
		sym("@keyword.debug")({ Debug }),
		LspCodeLens({ fg = "#636da6" }),
		LspCodeLensSeparator({ LspCodeLens }),
		LspInlayHint({ fg = "#3d4267" }),
		LspReferenceRead({ bg = "#3b4261" }),
		LspReferenceText({ bg = "#3b4261" }),
		LspReferenceTarget({ LspReferenceText }),
		LspReferenceWrite({ bg = "#3b4261" }),
		LspSignatureActiveParameter({ bg = "#262f50", gui = "bold" }),
		BlinkCmpSignatureHelpActiveParameter({ LspSignatureActiveParameter }),
		DiagnosticError({ fg = "#c53b53" }),
		DiagnosticFloatingError({ DiagnosticError }),
		DiagnosticVirtualLinesError({ DiagnosticError }),
		DiagnosticSignError({ DiagnosticError }),
		OilOrphanLinkTarget({ DiagnosticError }),
		OilDelete({ DiagnosticError }),
		DiagnosticWarn({ fg = "#ffc777" }),
		DiagnosticFloatingWarn({ DiagnosticWarn }),
		DiagnosticVirtualLinesWarn({ DiagnosticWarn }),
		DiagnosticSignWarn({ DiagnosticWarn }),
		MiniDepsMsgBreaking({ DiagnosticWarn }),
		OilMove({ DiagnosticWarn }),
		DiagnosticInfo({ fg = "#0db9d7" }),
		DiagnosticFloatingInfo({ DiagnosticInfo }),
		DiagnosticVirtualLinesInfo({ DiagnosticInfo }),
		DiagnosticSignInfo({ DiagnosticInfo }),
		MiniDepsInfo({ DiagnosticInfo }),
		OilCreate({ DiagnosticInfo }),
		DiagnosticHint({ fg = "#009955" }),
		DiagnosticFloatingHint({ DiagnosticHint }),
		DiagnosticVirtualLinesHint({ DiagnosticHint }),
		DiagnosticSignHint({ DiagnosticHint }),
		MiniDepsHint({ DiagnosticHint }),
		OilCopy({ DiagnosticHint }),
		DiagnosticOk({ fg = "nvimlightgreen" }),
		DiagnosticFloatingOk({ DiagnosticOk }),
		DiagnosticVirtualTextOk({ DiagnosticOk }),
		DiagnosticVirtualLinesOk({ DiagnosticOk }),
		DiagnosticSignOk({ DiagnosticOk }),
		DiagnosticVirtualTextError({ bg = "#130707", fg = "#ff0000" }),
		DiagnosticVirtualTextWarn({ bg = "#38343d", fg = "#ffc777" }),
		DiagnosticVirtualTextInfo({ bg = "#203346", fg = "#0db9d7" }),
		DiagnosticVirtualTextHint({ bg = "#25270e", fg = "#ffba03" }),
		DiagnosticUnnecessary({ fg = "#000000" }),
		Comment({ fg = "#636da6", gui = "italic" }),
		sym("@comment")({ Comment }),
		MiniJump2dDim({ Comment }),
		MiniDepsPlaceholder({ Comment }),
		MiniDepsTitleSame({ Comment }),
		OilHidden({ Comment }),
		OilLinkTarget({ Comment }),
		OilTrashSourcePath({ Comment }),
		luaComment({ Comment }),
		sym("@variable")({ fg = "#c8d3f5" }),
		sym("@lsp.type.namespace.python")({ sym("@variable") }),
		sym("@lsp.type.generic")({ sym("@variable") }),
		LspKindVariable({ sym("@variable") }),
		sym("@lsp.typemod.variable.injected")({ sym("@variable") }),
		sym("@variable.builtin")({ fg = "#ff757f" }),
		sym("@lsp.type.selfKeyword")({ sym("@variable.builtin") }),
		sym("@lsp.type.selfTypeKeyword")({ sym("@variable.builtin") }),
		sym("@lsp.typemod.variable.defaultLibrary")({ sym("@variable.builtin") }),
		sym("@namespace.builtin")({ sym("@variable.builtin") }),
		sym("@variable.parameter")({ fg = "#ffc777" }),
		sym("@lsp.type.parameter")({ sym("@variable.parameter") }),
		sym("@variable.parameter.builtin")({ fg = "#f4c990" }),
		sym("@module")({ fg = "#00ff9c" }),
		sym("@lsp.type.namespace")({ sym("@module") }),
		LspKindNamespace({ sym("@module") }),
		LspKindModule({ sym("@module") }),
		LspKindPackage({ sym("@module") }),
		sym("@module.builtin")({ fg = "#ff757f" }),
		sym("@label")({ fg = "#82aaff" }),
		String({ fg = "#c3e88d" }),
		sym("@string")({ String }),
		NvimString({ String }),
		TelescopePreviewSize({ String }),
		TelescopePreviewExecute({ String }),
		sym("@markup.raw")({ String }),
		luaString2({ String }),
		luaString({ String }),
		sym("@string.regexp")({ fg = "#b4f9f8" }),
		sym("@lsp.type.regexp")({ sym("@string.regexp") }),
		sym("@string.escape")({ fg = "#c099ff" }),
		sym("@lsp.type.escapeSequence")({ sym("@string.escape") }),
		sym("@type.builtin")({ fg = "#589ed7" }),
		sym("@lsp.typemod.enum.defaultLibrary")({ sym("@type.builtin") }),
		sym("@lsp.typemod.struct.defaultLibrary")({ sym("@type.builtin") }),
		sym("@lsp.typemod.class.defaultLibrary")({ sym("@type.builtin") }),
		sym("@lsp.type.builtinType")({ sym("@type.builtin") }),
		sym("@property")({ fg = "#4fd6be" }),
		sym("@lsp.type.property")({ sym("@property") }),
		dosIniLabel({ sym("@property") }),
		LspKindProperty({ sym("@property") }),
		sym("@tag.attribute")({ sym("@property") }),
		Identifier({ fg = "#c099ff" }),
		NvimIdentifier({ Identifier }),
		TelescopeMultiIcon({ Identifier }),
		TelescopeResultsIdentifier({ Identifier }),
		sym("@markup.link.label.symbol")({ Identifier }),
		luaFunc({ Identifier }),
		Function({ fg = "#82aaff" }),
		sym("@function")({ Function }),
		sym("@function.method")({ Function }),
		TelescopeResultsFunction({ Function }),
		TelescopeResultsField({ Function }),
		TelescopeResultsClass({ Function }),
		luaMetaMethod({ Function }),
		luaFunction({ Function }),
		sym("@constructor")({ fg = "#c099ff" }),
		LspKindConstructor({ sym("@constructor") }),
		sym("@operator")({ fg = "#89ddff" }),
		sym("@lsp.type.operator")({ sym("@operator") }),
		sym("@keyword.operator")({ sym("@operator") }),
		LspKindOperator({ sym("@operator") }),
		sym("@lsp.typemod.operator.injected")({ sym("@operator") }),
		Operator({ fg = "#89ddff" }),
		NvimAssignment({ Operator }),
		NvimOperator({ Operator }),
		TelescopeResultsOperator({ Operator }),
		luaOperator({ Operator }),
		sym("@keyword")({ fg = "#fca7ea" }),
		sym("@lsp.type.keyword")({ sym("@keyword") }),
		sym("@type.qualifier")({ sym("@keyword") }),
		sym("@keyword.coroutine")({ sym("@keyword") }),
		sym("@keyword.return")({ sym("@keyword") }),
		sym("@lsp.typemod.keyword.injected")({ sym("@keyword") }),
		sym("@punctuation.special")({ fg = "#89ddff" }),
		sym("@comment.error")({ fg = "#c53b53" }),
		sym("@comment.warning")({ fg = "#ffc777" }),
		sym("@comment.note")({ fg = "#4fd6be" }),
		sym("@comment.todo")({ fg = "#82aaff" }),
		Todo({ bg = "#ffc777", fg = "#222436" }),
		luaTodo({ Todo }),
		sym("@markup.strong")({ gui = "bold" }),
		sym("@markup.italic")({ gui = "italic" }),
		sym("@markup.strikethrough")({ gui = "strikethrough" }),
		sym("@markup.underline")({ gui = "underline" }),
		sym("@markup.link")({ fg = "#4fd6be" }),
		LspKindReference({ sym("@markup.link") }),
		WhichKeyIcon({ sym("@markup.link") }),
		Added({ fg = "nvimlightgreen" }),
		Removed({ fg = "nvimlightred" }),
		Changed({ fg = "nvimlightcyan" }),
		sym("@markup.heading.1.delimiter.vimdoc")({ fg = "#4fd6be" }),
		sym("@markup.heading.2.delimiter.vimdoc")({ fg = "#4fd6be" }),
		sym("@lsp.type.interface")({ fg = "#83c3fc" }),
		LspKindInterface({ sym("@lsp.type.interface") }),
		DiagnosticDeprecated({ sp = "nvimlightred", gui = "strikethrough" }),
		sym("@lsp.mod.deprecated")({ DiagnosticDeprecated }),
		FloatShadow({ bg = "nvimdarkgrey4", blend = 80 }),
		FloatShadowThrough({ bg = "nvimdarkgrey4", blend = 100 }),
		MatchParen({ fg = "#ff966c", gui = "bold" }),
		RedrawDebugClear({ bg = "nvimdarkyellow" }),
		RedrawDebugComposed({ bg = "nvimdarkgreen" }),
		RedrawDebugRecompose({ bg = "nvimdarkred" }),
		Error({ fg = "#c53b53" }),
		NvimInvalid({ Error }),
		luaParenError({ Error }),
		luaError({ Error }),
		DiagnosticUnderlineError({ sp = "#c53b53", gui = "undercurl" }),
		DiagnosticUnderlineWarn({ sp = "#ffc777", gui = "undercurl" }),
		DiagnosticUnderlineInfo({ sp = "#0db9d7", gui = "undercurl" }),
		DiagnosticUnderlineHint({ sp = "#4fd6be", gui = "undercurl" }),
		DiagnosticUnderlineOk({ sp = "nvimlightgreen", gui = "underline" }),
		NvimInternalError({ bg = "red", fg = "red" }),
		NvimFigureBrace({ NvimInternalError }),
		NvimSingleQuotedUnknownEscape({ NvimInternalError }),
		NvimInvalidSingleQuotedUnknownEscape({ NvimInternalError }),
		lualine_transparent({ fg = "#c8d3f5", gui = "nocombine" }),
		lualine_c_replace({ bg = "#112638", fg = "#c3ccdc", gui = "nocombine" }),
		lualine_b_replace({ bg = "#76ff03", fg = "#112638", gui = "nocombine" }),
		lualine_a_replace({ bg = "#ff1744", fg = "#112638", gui = "bold,nocombine" }),
		lualine_c_inactive({ bg = "#2c3043", fg = "#6c6f93", gui = "nocombine" }),
		lualine_b_inactive({ bg = "#76ff03", fg = "#112638", gui = "nocombine" }),
		lualine_a_inactive({ bg = "#2c3043", fg = "#6c6f93", gui = "bold,nocombine" }),
		lualine_c_visual({ bg = "#112638", fg = "#c3ccdc", gui = "nocombine" }),
		lualine_b_visual({ bg = "#76ff03", fg = "#112638", gui = "nocombine" }),
		lualine_a_visual({ bg = "#ff61ef", fg = "#112638", gui = "bold,nocombine" }),
		lualine_c_insert({ bg = "#112638", fg = "#c3ccdc", gui = "nocombine" }),
		lualine_b_insert({ bg = "#9abbe6", fg = "#112638", gui = "nocombine" }),
		lualine_a_insert({ bg = "#76ff03", fg = "#112638", gui = "bold,nocombine" }),
		lualine_c_command({ bg = "#112638", fg = "#c3ccdc", gui = "nocombine" }),
		lualine_b_command({ bg = "#76ff03", fg = "#112638", gui = "nocombine" }),
		lualine_a_command({ bg = "#ffda7b", fg = "#112638", gui = "bold,nocombine" }),
		lualine_c_normal({ bg = "#112638", fg = "#c3ccdc", gui = "nocombine" }),
		lualine_b_normal({ bg = "#9abbe6", fg = "#112638", gui = "nocombine" }),
		lualine_a_normal({ bg = "#2979ff", fg = "#112638", gui = "bold,nocombine" }),
		lualine_c_diagnostics_error_normal({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_insert({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_visual({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_replace({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_command({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_terminal({ bg = "#112638", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_error_inactive({ bg = "#2c3043", fg = "#c53b53", gui = "nocombine" }),
		lualine_c_diagnostics_warn_normal({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_insert({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_visual({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_replace({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_command({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_terminal({ bg = "#112638", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_warn_inactive({ bg = "#2c3043", fg = "#ffc777", gui = "nocombine" }),
		lualine_c_diagnostics_info_normal({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_insert({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_visual({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_replace({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_command({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_terminal({ bg = "#112638", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_info_inactive({ bg = "#2c3043", fg = "#0db9d7", gui = "nocombine" }),
		lualine_c_diagnostics_hint_normal({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_insert({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_visual({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_replace({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_command({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_terminal({ bg = "#112638", fg = "#009955", gui = "nocombine" }),
		lualine_c_diagnostics_hint_inactive({ bg = "#2c3043", fg = "#009955", gui = "nocombine" }),
		lualine_c_diff_added_normal({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_insert({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_visual({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_replace({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_command({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_terminal({ bg = "#112638", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_added_inactive({ bg = "#2c3043", fg = "#b8db87", gui = "nocombine" }),
		lualine_c_diff_modified_normal({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_insert({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_visual({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_replace({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_command({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_terminal({ bg = "#112638", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_modified_inactive({ bg = "#2c3043", fg = "#7ca1f2", gui = "nocombine" }),
		lualine_c_diff_removed_normal({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_insert({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_visual({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_replace({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_command({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_terminal({ bg = "#112638", fg = "#e26a75", gui = "nocombine" }),
		lualine_c_diff_removed_inactive({ bg = "#2c3043", fg = "#e26a75", gui = "nocombine" }),
		GitSignsAdd({ fg = "#b8db87" }),
		GitSignsUntracked({ GitSignsAdd }),
		GitSignsAddNr({ GitSignsAdd }),
		GitSignsAddCul({ GitSignsAdd }),
		GitSignsChange({ fg = "#7ca1f2" }),
		GitSignsChangedelete({ GitSignsChange }),
		GitSignsChangeNr({ GitSignsChange }),
		GitSignsChangeCul({ GitSignsChange }),
		GitSignsDelete({ fg = "#e26a75" }),
		GitSignsTopdelete({ GitSignsDelete }),
		GitSignsDeleteNr({ GitSignsDelete }),
		GitSignsDeleteCul({ GitSignsDelete }),
		GitSignsStagedAdd({ fg = "#597b60" }),
		GitSignsStagedChange({ fg = "#467c7b" }),
		GitSignsStagedDelete({ fg = "#7f605c" }),
		GitSignsStagedChangedelete({ fg = "#467c7b" }),
		GitSignsStagedTopdelete({ fg = "#7f605c" }),
		GitSignsStagedUntracked({ fg = "#597b60" }),
		GitSignsStagedAddNr({ fg = "#597b60" }),
		GitSignsStagedChangeNr({ fg = "#467c7b" }),
		GitSignsStagedDeleteNr({ fg = "#7f605c" }),
		GitSignsStagedChangedeleteNr({ fg = "#467c7b" }),
		GitSignsStagedTopdeleteNr({ fg = "#7f605c" }),
		GitSignsStagedUntrackedNr({ fg = "#597b60" }),
		GitSignsStagedAddLn({ bg = "#005523", fg = "#77787c" }),
		GitSignsStagedChangeLn({ bg = "#4f5258", fg = "#77787c" }),
		GitSignsStagedChangedeleteLn({ bg = "#4f5258", fg = "#77787c" }),
		GitSignsStagedUntrackedLn({ bg = "#005523", fg = "#77787c" }),
		GitSignsStagedAddCul({ fg = "#597b60" }),
		GitSignsStagedChangeCul({ fg = "#467c7b" }),
		GitSignsStagedDeleteCul({ fg = "#7f605c" }),
		GitSignsStagedChangedeleteCul({ fg = "#467c7b" }),
		GitSignsStagedTopdeleteCul({ fg = "#7f605c" }),
		GitSignsStagedUntrackedCul({ fg = "#597b60" }),
		TelescopeBorder({ bg = "#1e2030", fg = "#589ed7" }),
		TelescopeTitle({ TelescopeBorder }),
		TelescopeNormal({ bg = "#1e2030", fg = "#c8d3f5" }),
		TelescopeSelection({ bg = "#252530", fg = "#ffffff" }),
		TelescopeSelectionCaret({ TelescopeSelection }),
		TelescopeMatching({ fg = "#c586c0", gui = "bold" }),
		TelescopeResultsBorder({ bg = "#05050a", fg = "#05050a" }),
		TelescopeResultsNormal({ bg = "#05050a", fg = "#a0c0d0" }),
		TelescopePreviewBorder({ bg = "#1a1a22", fg = "#1a1a22" }),
		TelescopePreviewNormal({ bg = "#1a1a22", fg = "#a0c0d0" }),
		TelescopePreviewMessage({ TelescopePreviewNormal }),
		TelescopePromptPrefix({ fg = "#c586c0", gui = "bold" }),
		TelescopePromptBorder({ bg = "#1a1a22", fg = "#1a1a22" }),
		TelescopePromptNormal({ bg = "#1a1a22", fg = "#ffffff" }),
		TelescopeResultsComment({ fg = "#545c7e" }),
		MiniStatuslineDevinfo({ bg = "#3b4261", fg = "#828bb8" }),
		sym("@lsp.typemod.typeAlias.defaultLibrary")({ fg = "#589ed7" }),
		MiniDepsTitleUpdate({ bg = "#b8db87", fg = "#1b1d2b" }),
		MiniHipatternsHack({ bg = "#ffc777", fg = "#1b1d2b", gui = "bold" }),
		sym("@constructor.tsx")({ fg = "#65bcff" }),
		MiniPickPrompt({ bg = "#1e2030", fg = "#0db9d7" }),
		sym("@markup.heading.4.markdown")({ fg = "#4fd6be", gui = "bold" }),
		Italic({ fg = "#c8d3f5", gui = "italic" }),
		NormalSB({ bg = "#1e2030", fg = "#828bb8" }),
		sym("@markup.heading.6.markdown")({ fg = "#fca7ea", gui = "bold" }),
		diffChanged({ bg = "#252a3f", fg = "#7ca1f2" }),
		diffRemoved({ bg = "#3a273a", fg = "#e26a75" }),
		MiniDepsChangeRemoved({ diffRemoved }),
		sym("@markup.emphasis")({ gui = "italic" }),
		helpCommand({ bg = "#444a73", fg = "#82aaff" }),
		diffAdded({ bg = "#273849", fg = "#b8db87" }),
		MiniDepsChangeAdded({ diffAdded }),
		htmlH2({ fg = "#82aaff", gui = "bold" }),
		MiniTrailspace({ bg = "#ff757f" }),
		CmpDocBorder({ bg = "#05050a", fg = "#05050a" }),
		CmpDoc({ bg = "#05050a", fg = "#a0c0d0" }),
		CmpItemMenu({ fg = "#607080" }),
		CmpItemKindClass({ fg = "#80d4a0" }),
		CmpItemKindText({ fg = "#a0c0d0" }),
		CmpItemKindInterface({ fg = "#7fd1e0" }),
		CmpItemKindEnum({ fg = "#80d4a0" }),
		CmpItemKindField({ fg = "#ffc66d" }),
		CmpItemKindProperty({ fg = "#c586c0" }),
		MiniJump({ bg = "#ff007c", fg = "#ffffff" }),
		MiniTablineFill({ bg = "#1b1d2b" }),
		MiniTablineModifiedHidden({ bg = "#1e2030", fg = "#bd9664" }),
		CmpItemKindSnippet({ fg = "#a0c0d0" }),
		MiniPickBorderText({ bg = "#1e2030", fg = "#4fd6be" }),
		CmpItemKindKeyword({ fg = "#c586c0" }),
		sym("@variable.member")({ fg = "#4fd6be" }),
		LspKindKey({ sym("@variable.member") }),
		LspKindField({ sym("@variable.member") }),
		CmpItemKindMethod({ fg = "#a0c0d0" }),
		BlinkCmpKindCodeium({ fg = "#4fd6be" }),
		BlinkCmpKindDefault({ fg = "#828bb8" }),
		MiniCursorword({ bg = "#3b4261" }),
		CmpItemKindVariable({ fg = "#ffc66d" }),
		MiniJump2dSpotUnique({ fg = "#ff966c", gui = "bold,nocombine" }),
		sym("@markup.heading.3.markdown")({ fg = "#c3e88d", gui = "bold" }),
		CmpPmenuThumb({ bg = "#4a4a4a" }),
		CmpItemKindFunction({ fg = "#a0c0d0" }),
		sym("@punctuation.bracket")({ fg = "#f3c623" }),
		LspKindArray({ sym("@punctuation.bracket") }),
		debugPC({ bg = "#1e2030" }),
		sym("@punctuation.special.markdown")({ fg = "#ff966c" }),
		sym("@markup.heading.2.markdown")({ fg = "#ffc777", gui = "bold" }),
		healthSuccess({ fg = "#4fd6be" }),
		MiniHipatternsNote({ bg = "#4fd6be", fg = "#1b1d2b", gui = "bold" }),
		healthError({ fg = "#c53b53" }),
		diffFile({ fg = "#82aaff" }),
		diffLine({ fg = "#636da6" }),
		sym("@tag.javascript")({ fg = "#ff757f" }),
		sym("@markup.heading.7.markdown")({ fg = "#ff966c", gui = "bold" }),
		sym("@lsp.type.unresolvedReference")({ sp = "#c53b53", gui = "undercurl" }),
		MiniStatuslineInactive({ bg = "#1e2030", fg = "#82aaff" }),
		sym("@lsp.typemod.type.defaultLibrary")({ fg = "#589ed7" }),
		MiniSurround({ bg = "#ff966c", fg = "#1b1d2b" }),
		MiniStatuslineModeVisual({ bg = "#c099ff", fg = "#1b1d2b", gui = "bold" }),
		CmpItemKind({ fg = "#7fd1e0" }),
		CmpItemAbbrMatch({ fg = "#c586c0", gui = "bold" }),
		CmpItemAbbr({ fg = "#a0c0d0" }),
		CmpPmenuSbar({ bg = "#0a0a10" }),
		CmpPmenuBorder({ bg = "#07070f", fg = "#07070f" }),
		CmpPmenuSel({ bg = "#252530", fg = "#ffffff" }),
		CmpPmenu({ bg = "#07070f", fg = "#a0c0d0" }),
		debugBreakpoint({ bg = "#203346", fg = "#0db9d7" }),
		htmlH1({ fg = "#c099ff", gui = "bold" }),
		sym("@markup.list")({ fg = "#89ddff" }),
		sym("@lsp.type.formatSpecifier")({ sym("@markup.list") }),
		sym("@markup.list.unchecked")({ fg = "#82aaff" }),
		sym("@tag.tsx")({ fg = "#ff757f" }),
		sym("@markup.list.markdown")({ fg = "#ff966c", gui = "bold" }),
		sym("@markup.heading.5.markdown")({ fg = "#c099ff", gui = "bold" }),
		Foo({ bg = "#ff007c", fg = "#c8d3f5" }),
		MiniDiffSignChange({ fg = "#7ca1f2" }),
		MiniDiffSignAdd({ fg = "#b8db87" }),
		MiniDiffSignDelete({ fg = "#e26a75" }),
		BlinkCmpKindCopilot({ fg = "#4fd6be" }),
		BlinkCmpKindTabNine({ fg = "#4fd6be" }),
		BlinkCmpGhostText({ fg = "#444a73" }),
		BlinkCmpSignatureHelp({ bg = "#1e2030", fg = "#c8d3f5" }),
		SignColumnSB({ bg = "#1e2030", fg = "#3b4261" }),
		BlinkCmpDocBorder({ bg = "#1a1a22", fg = "#1a1a22" }),
		Bold({ fg = "#c8d3f5", gui = "bold" }),
		sym("@markup.raw.markdown_inline")({ bg = "#444a73", fg = "#82aaff" }),
		MiniIndentscopePrefix({ gui = "nocombine" }),
		MiniHipatternsFixme({ bg = "#c53b53", fg = "#1b1d2b", gui = "bold" }),
		MiniHipatternsTodo({ bg = "#0db9d7", fg = "#1b1d2b", gui = "bold" }),
		BlinkCmpLabel({ fg = "#c8d3f5" }),
		BlinkCmpLabelDeprecated({ fg = "#3b4261", gui = "strikethrough" }),
		LazyProgressDone({ fg = "#ff007c", gui = "bold" }),
		LazyProgressTodo({ fg = "#3b4261", gui = "bold" }),
		WhichKeyNormal({ bg = "#1e2030" }),
		MiniFilesTitleFocused({ bg = "#1e2030", fg = "#589ed7", gui = "bold" }),
		MiniFilesFile({ fg = "#c8d3f5" }),
		MiniStatuslineModeReplace({ bg = "#ff757f", fg = "#1b1d2b", gui = "bold" }),
		MiniStatuslineModeCommand({ bg = "#ffc777", fg = "#1b1d2b", gui = "bold" }),
		MiniStatuslineFilename({ bg = "#2f334d", fg = "#828bb8" }),
		MiniCompletionActiveParameter({ gui = "underline" }),
		WhichKeySeparator({ fg = "#636da6" }),
		WhichKey({ fg = "#86e1fc" }),
		WhichKeyValue({ fg = "#737aa2" }),
		WhichKeyDesc({ fg = "#c099ff" }),
		sym("@string.documentation")({ fg = "#ffc777" }),
		MiniDepsTitleError({ bg = "#e26a75", fg = "#1b1d2b" }),
		sym("@markup.heading.1.markdown")({ fg = "#82aaff", gui = "bold" }),
		sym("@punctuation.delimiter")({ fg = "#89ddff" }),
		sym("@markup.list.checked")({ fg = "#4fd6be" }),
		sym("@markup.heading.8.markdown")({ fg = "#ff757f", gui = "bold" }),
		MiniJump2dSpot({ fg = "#ff007c", gui = "bold,nocombine" }),
		MiniTablineModifiedVisible({ bg = "#1e2030", fg = "#ffc777" }),
		sym("@comment.info")({ fg = "#0db9d7" }),
		qfLineNr({ fg = "#737aa2" }),
		MiniTablineModifiedCurrent({ bg = "#3b4261", fg = "#ffc777" }),
		MiniTablineTabpagesection({ bg = "#3b4261" }),
		MiniIconsYellow({ fg = "#ffc777" }),
		WhichKeyIconYellow({ MiniIconsYellow }),
		MiniIconsOrange({ fg = "#ff966c" }),
		WhichKeyIconOrange({ MiniIconsOrange }),
		MiniIconsAzure({ fg = "#0db9d7" }),
		WhichKeyIconAzure({ MiniIconsAzure }),
		MiniIconsPurple({ fg = "#fca7ea" }),
		WhichKeyIconPurple({ MiniIconsPurple }),
		MiniIconsCyan({ fg = "#4fd6be" }),
		WhichKeyIconCyan({ MiniIconsCyan }),
		MiniStatuslineModeNormal({ bg = "#82aaff", fg = "#1b1d2b", gui = "bold" }),
		MiniIconsRed({ fg = "#ff757f" }),
		WhichKeyIconRed({ MiniIconsRed }),
		MiniCursorwordCurrent({ bg = "#3b4261" }),
		BlinkCmpKindSupermaven({ fg = "#4fd6be" }),
		MiniJump2dSpotAhead({ bg = "#1e2030", fg = "#4fd6be", gui = "nocombine" }),
		BlinkCmpSignatureHelpBorder({ bg = "#1e2030", fg = "#589ed7" }),
		BlinkCmpLabelMatch({ fg = "#c586c0", gui = "bold" }),
		SupermavenSuggestion({ fg = "#444a73" }),
		BlinkCmpDoc({ bg = "#1a1a22", fg = "#a0c0d0" }),
		BlinkCmpMenu({ bg = "#0f0f14", fg = "#a0c0d0" }),
		BlinkCmpMenuBorder({ bg = "#0f0f14", fg = "#a0c0d0" }),
		MiniTestFail({ fg = "#ff757f", gui = "bold" }),
		MiniStarterQuery({ fg = "#0db9d7" }),
		MiniTestPass({ fg = "#c3e88d", gui = "bold" }),
		MiniStarterSection({ fg = "#65bcff" }),
		MiniStarterInactive({ fg = "#636da6", gui = "italic" }),
		MiniStarterItemBullet({ fg = "#589ed7" }),
		MiniStarterItem({ fg = "#c8d3f5" }),
		MiniStarterFooter({ fg = "#ffc777", gui = "italic" }),
		MiniStarterCurrent({ gui = "nocombine" }),
		diffNewFile({ bg = "#273849", fg = "#65bcff" }),
		qfFileName({ fg = "#82aaff" }),
		MiniStarterHeader({ fg = "#82aaff" }),
		diffOldFile({ bg = "#3a273a", fg = "#65bcff" }),
		MiniTestEmphasis({ gui = "bold" }),
		diffIndexLine({ fg = "#c099ff" }),
		MiniTablineHidden({ bg = "#1e2030", fg = "#737aa2" }),
		healthWarning({ fg = "#ffc777" }),
		sym("@keyword.function")({ fg = "#c099ff" }),
		MiniStarterItemPrefix({ fg = "#ffc777" }),
		MiniAnimateCursor({ gui = "reverse,nocombine" }),
		MiniTablineVisible({ bg = "#1e2030", fg = "#c8d3f5" }),
		LspInfoBorder({ bg = "#1e2030", fg = "#589ed7" }),
		MiniIconsGreen({ fg = "#c3e88d" }),
		WhichKeyIconGreen({ MiniIconsGreen }),
		helpExample({ fg = "#636da6" }),
		MiniIconsGrey({ fg = "#c8d3f5" }),
		WhichKeyIconGrey({ MiniIconsGrey }),
		MiniIconsBlue({ fg = "#82aaff" }),
		WhichKeyIconBlue({ MiniIconsBlue }),
		sym("@tag.delimiter.tsx")({ fg = "#6582c3" }),
		MiniTablineCurrent({ bg = "#3b4261", fg = "#c8d3f5" }),
		WhichKeyGroup({ fg = "#82aaff" }),
		MiniStatuslineModeInsert({ bg = "#c3e88d", fg = "#1b1d2b", gui = "bold" }),
		MiniIndentscopeSymbol({ fg = "#65bcff", gui = "nocombine" }),
		sym("@comment.hint")({ fg = "#4fd6be" }),
		MiniStatuslineModeOther({ bg = "#4fd6be", fg = "#1b1d2b", gui = "bold" }),
		MiniStatuslineFileinfo({ bg = "#3b4261", fg = "#828bb8" }),
		DevIconGroovy({ fg = "#4a687c" }),
		DevIconBackup({ fg = "#6d8086" }),
		DevIconCommitlintConfig({ fg = "#2b9689" }),
		DevIconM3u8({ fg = "#ed95ae" }),
		DevIconGoWork({ fg = "#00add8" }),
		DevIconCodeOfConduct({ fg = "#e41662" }),
		DevIconPm({ fg = "#519aba" }),
		DevIconHexadecimal({ fg = "#2e63ff" }),
		DevIconGoSum({ fg = "#00add8" }),
		DevIconCrystal({ fg = "#c8c8c8" }),
		DevIconCobol({ fg = "#005ca5" }),
		DevIconXml({ fg = "#e37933" }),
		DevIconHeex({ fg = "#a074c4" }),
		DevIconTxt({ fg = "#89e051" }),
		DevIconNPMIgnore({ fg = "#e8274b" }),
		DevIconDockerfile({ fg = "#458ee6" }),
		DevIconGitIgnore({ fg = "#f54d27" }),
		DevIconKotlin({ fg = "#7f52ff" }),
		DevIconGitAttributes({ fg = "#f54d27" }),
		DevIconGitModules({ fg = "#f54d27" }),
		DevIconWebOpenFontFormat({ fg = "#ececec" }),
		DevIconGitConfig({ fg = "#f54d27" }),
		DevIconSpecTs({ fg = "#519aba" }),
		DevIconJavaScriptReactSpec({ fg = "#20c2e3" }),
		DevIconSpecJs({ fg = "#cbcb41" }),
		DevIconVsix({ fg = "#854cc7" }),
		DevIconSolveSpace({ fg = "#839463" }),
		DevIconLabView({ fg = "#fec60a" }),
		DevIconSolidWorksPrt({ fg = "#839463" }),
		DevIconHs({ fg = "#a074c4" }),
		DevIconSystemVerilog({ fg = "#019833" }),
		DevIconSketchUp({ fg = "#839463" }),
		DevIconSha512({ fg = "#8c86af" }),
		DevIconHbs({ fg = "#f0772b" }),
		DevIconSway({ fg = "#68751c" }),
		DevIconSvg({ fg = "#ffb13b" }),
		DevIconHaml({ fg = "#eaeae1" }),
		DevIconLhs({ fg = "#a074c4" }),
		DevIconSha224({ fg = "#8c86af" }),
		DevIconSha1({ fg = "#8c86af" }),
		DevIconStyl({ fg = "#8dc149" }),
		DevIconTrueTypeFont({ fg = "#ececec" }),
		DevIconGradle({ fg = "#005f87" }),
		DevIconTypoScriptConfig({ fg = "#ff8700" }),
		DevIconGraphQL({ fg = "#e535ab" }),
		DevIconTorrent({ fg = "#44cda8" }),
		DevIconWavPackCorrection({ fg = "#00afff" }),
		DevIconWavPack({ fg = "#00afff" }),
		DevIconVRML({ fg = "#888888" }),
		DevIconMd({ fg = "#dddddd" }),
		DevIconBazelWorkspace({ fg = "#89e051" }),
		DevIconTypeScriptReactTest({ fg = "#1354bf" }),
		DevIconHtml({ fg = "#e44d26" }),
		DevIconTestTs({ fg = "#519aba" }),
		DevIconGodotTextResource({ fg = "#6d8086" }),
		DevIconTestJs({ fg = "#cbcb41" }),
		DevIconMotoko({ fg = "#9772fb" }),
		DevIconQt({ fg = "#40cd52" }),
		DevIconFsx({ fg = "#519aba" }),
		DevIconLocalization({ fg = "#2596be" }),
		DevIconFsi({ fg = "#519aba" }),
		DevIconTcl({ fg = "#1e5cb3" }),
		DevIconAndroid({ fg = "#34a853" }),
		DevIconSolus({ fg = "#4b5163" }),
		DevIconSvgz({ fg = "#ffb13b" }),
		DevIconGitLogo({ fg = "#f14c28" }),
		DevIconPub({ fg = "#e3c58e" }),
		DevIconEndeavour({ fg = "#7b3db9" }),
		DevIconRockyLinux({ fg = "#0fb37d" }),
		DevIconFortran({ fg = "#734f96" }),
		DevIconDevuan({ fg = "#404a52" }),
		DevIconQubesOS({ fg = "#3774d8" }),
		DevIconC({ fg = "#599eff" }),
		DevIconFish({ fg = "#4d5a5e" }),
		DevIconPuppyLinux({ fg = "#a2aeb9" }),
		DevIconCrystalLinux({ fg = "#a900ff" }),
		DevIconFennel({ fg = "#fff3d7" }),
		DevIcon3DObjectFile({ fg = "#888888" }),
		DevIconPop_OS({ fg = "#48b9c7" }),
		DevIconBigLinux({ fg = "#189fc8" }),
		DevIconYml({ fg = "#6d8086" }),
		DevIconMint({ fg = "#87c095" }),
		DevIconArtix({ fg = "#41b4d7" }),
		DevIconPulseCodeModulation({ fg = "#0075aa" }),
		DevIconopenSUSE({ fg = "#6fb424" }),
		DevIconPart({ fg = "#44cda8" }),
		DevIconArchlabs({ fg = "#503f42" }),
		DevIconOut({ fg = "#9f0500" }),
		DevIconArchcraft({ fg = "#86bba3" }),
		DevIconStorybookVue({ fg = "#ff4785" }),
		DevIconApple({ fg = "#a2aaad" }),
		DevIconSignature({ fg = "#e37933" }),
		DevIconOggVideo({ fg = "#fd971f" }),
		DevIconStorybookTsx({ fg = "#ff4785" }),
		DevIconAOSC({ fg = "#c00000" }),
		DevIconStorybookTypeScript({ fg = "#ff4785" }),
		DevIconLibreOfficeWriter({ fg = "#2dcbfd" }),
		DevIconStorybookSvelte({ fg = "#ff4785" }),
		DevIconAlpine({ fg = "#0d597f" }),
		DevIconStorybookMjs({ fg = "#ff4785" }),
		DevIconRss({ fg = "#fb9d3b" }),
		DevIconStorybookJsx({ fg = "#ff4785" }),
		DevIconAlmalinux({ fg = "#ff4649" }),
		DevIconXul({ fg = "#e37933" }),
		DevIconLocOS({ fg = "#fab402" }),
		DevIconLibreOfficeImpress({ fg = "#fe9c45" }),
		DevIconThunderbird({ fg = "#137be1" }),
		DevIconLibreOfficeGraphics({ fg = "#fffb57" }),
		DevIconKubuntu({ fg = "#007ac2" }),
		DevIconOggSpeexAudio({ fg = "#0075aa" }),
		DevIconKDEneon({ fg = "#20a6a4" }),
		DevIconTypeScriptReactSpec({ fg = "#1354bf" }),
		DevIconLicense({ fg = "#d0bf41" }),
		DevIconNodeModules({ fg = "#e8274b" }),
		DevIconFsscript({ fg = "#519aba" }),
		DevIconFsharp({ fg = "#519aba" }),
		DevIconIllumos({ fg = "#ff430f" }),
		DevIconMixLock({ fg = "#a074c4" }),
		DevIconPyc({ fg = "#ffe291" }),
		DevIconPyo({ fg = "#ffe291" }),
		DevIconSql({ fg = "#dad8d8" }),
		DevIconPsb({ fg = "#519aba" }),
		DevIconVagrantfile({ fg = "#1563ff" }),
		DevIconGuix({ fg = "#ffcc00" }),
		DevIconWasm({ fg = "#5c4cdb" }),
		DevIconWebpack({ fg = "#519aba" }),
		DevIconXcPlayground({ fg = "#e37933" }),
		DevIconSuo({ fg = "#854cc7" }),
		DevIconSublime({ fg = "#e37933" }),
		DevIconMpv({ fg = "#3b1342" }),
		DevIconRlib({ fg = "#dea584" }),
		DevIconPyd({ fg = "#ffe291" }),
		DevIconPsd({ fg = "#519aba" }),
		DevIconProcfile({ fg = "#a074c4" }),
		DevIconOpenTypeFont({ fg = "#ececec" }),
		DevIconOpusAudioFile({ fg = "#0075aa" }),
		DevIconLiquid({ fg = "#95bf47" }),
		DevIconMaterial({ fg = "#b83998" }),
		DevIconYaml({ fg = "#6d8086" }),
		DevIconBoundaryRepresentation({ fg = "#839463" }),
		DevIconGodotProject({ fg = "#6d8086" }),
		DevIconBinaryGLTF({ fg = "#ffb13b" }),
		DevIconGemfile({ fg = "#701516" }),
		DevIconDropbox({ fg = "#0061fe" }),
		DevIconCts({ fg = "#519aba" }),
		DevIconMts({ fg = "#519aba" }),
		DevIconCson({ fg = "#cbcb41" }),
		DevIconCp({ fg = "#519aba" }),
		DevIconCoffee({ fg = "#cbcb41" }),
		DevIconBrewfile({ fg = "#701516" }),
		DevIconPyi({ fg = "#ffbc03" }),
		DevIconAvif({ fg = "#a074c4" }),
		DevIconAPL({ fg = "#24a148" }),
		DevIconPyw({ fg = "#5aa7e4" }),
		DevIconVerilog({ fg = "#019833" }),
		DevIconPxi({ fg = "#5aa7e4" }),
		DevIconRazorPage({ fg = "#512bd4" }),
		DevIconCsv({ fg = "#89e051" }),
		DevIconAzureCli({ fg = "#0078d4" }),
		DevIconcudah({ fg = "#a074c4" }),
		DevIconCue({ fg = "#ed95ae" }),
		DevIconDart({ fg = "#03589c" }),
		DevIconVHDL({ fg = "#019833" }),
		DevIconDesktopEntry({ fg = "#563d7c" }),
		DevIconBat({ fg = "#c1f12e" }),
		DevIconIni({ fg = "#6d8086" }),
		DevIconDot({ fg = "#30638e" }),
		DevIconGv({ fg = "#30638e" }),
		DevIconXSettingsdConf({ fg = "#e54d18" }),
		DevIconTemplate({ fg = "#dbbd30" }),
		DevIconTempl({ fg = "#dbbd30" }),
		DevIconxmonad({ fg = "#fd4d5d" }),
		DevIconWranglerConfig({ fg = "#f48120" }),
		DevIconLock({ fg = "#bbbbbb" }),
		DevIconEex({ fg = "#a074c4" }),
		DevIconTerraform({ fg = "#5f43e9" }),
		DevIconElf({ fg = "#9f0500" }),
		DevIconExs({ fg = "#a074c4" }),
		DevIconWeston({ fg = "#ffbb01" }),
		DevIconEpp({ fg = "#ffa61a" }),
		DevIconCpp({ fg = "#519aba" }),
		DevIconErl({ fg = "#b83998" }),
		DevIconVLC({ fg = "#ee7a00" }),
		DevIconHrl({ fg = "#b83998" }),
		DevIconVercel({ fg = "#ffffff" }),
		DevIconConfig({ fg = "#6d8086" }),
		DevIconLinux({ fg = "#fdfdfb" }),
		DevIconTSConfig({ fg = "#519aba" }),
		DevIconBicepParameters({ fg = "#9f74b3" }),
		DevIconBicep({ fg = "#519aba" }),
		DevIconTmux({ fg = "#14ba19" }),
		DevIconAwk({ fg = "#4d5a5e" }),
		DevIconKiCadSymbolTable({ fg = "#ffffff" }),
		DevIconClangConfig({ fg = "#6d8086" }),
		DevIconConda({ fg = "#43b02a" }),
		DevIconSvelteConfig({ fg = "#ff3e00" }),
		DevIconGradleSettings({ fg = "#005f87" }),
		DevIconZshrc({ fg = "#89e051" }),
		DevIconZshprofile({ fg = "#89e051" }),
		DevIconSecurity({ fg = "#bec4c9" }),
		DevIconZshenv({ fg = "#89e051" }),
		DevIconAppleScript({ fg = "#6d8085" }),
		DevIconReadme({ fg = "#ededed" }),
		DevIconSub({ fg = "#ffb713" }),
		DevIconAdaBody({ fg = "#599eff" }),
		DevIconGPRBuildProject({ fg = "#6d8086" }),
		DevIconGDScript({ fg = "#6d8086" }),
		DevIconDump({ fg = "#dad8d8" }),
		DevIconPrettierConfig({ fg = "#4285f4" }),
		DevIconEjs({ fg = "#cbcb41" }),
		DevIconKotlinScript({ fg = "#7f52ff" }),
		DevIconMaven({ fg = "#7a0d21" }),
		DevIconNix({ fg = "#7ebae4" }),
		DevIconPlatformio({ fg = "#f6822b" }),
		DevIconBazelBuild({ fg = "#89e051" }),
		DevIconJl({ fg = "#a270ba" }),
		DevIconOdin({ fg = "#3882d2" }),
		DevIconPackageLockJson({ fg = "#7a0d21" }),
		DevIconJson5({ fg = "#cbcb41" }),
		DevIconLog({ fg = "#dddddd" }),
		DevIconMli({ fg = "#e37933" }),
		DevIconNuxtConfig({ fg = "#00c58e" }),
		DevIconRb({ fg = "#701516" }),
		DevIconNotebook({ fg = "#f57d01" }),
		DevIconWebmanifest({ fg = "#f1e05a" }),
		DevIconLXQtConfigFile({ fg = "#0192d3" }),
		DevIconScalaScript({ fg = "#cc3e44" }),
		DevIconMojo({ fg = "#ff4c1f" }),
		DevIconCjs({ fg = "#cbcb41" }),
		DevIconJs({ fg = "#cbcb41" }),
		DevIconMjs({ fg = "#f1e05a" }),
		DevIconi3({ fg = "#e8ebee" }),
		DevIconPp({ fg = "#ffa61a" }),
		DevIconJava({ fg = "#cc3e44" }),
		DevIconKdenliverc({ fg = "#83b8f2" }),
		DevIconTypeScript({ fg = "#519aba" }),
		DevIconKdenliveLayoutsrc({ fg = "#83b8f2" }),
		DevIconKDEglobals({ fg = "#1c99f3" }),
		DevIconTypst({ fg = "#0dbcc0" }),
		DevIconSig({ fg = "#e37933" }),
		DevIconArduino({ fg = "#56b6c2" }),
		DevIconAsc({ fg = "#576d7f" }),
		DevIconGentooBuild({ fg = "#4c416e" }),
		DevIconHurl({ fg = "#ff0288" }),
		DevIconPl({ fg = "#519aba" }),
		DevIconCinnamon({ fg = "#dc682e" }),
		DevIconBudgie({ fg = "#4e5361" }),
		DevIconR({ fg = "#2266ba" }),
		DevIconImg({ fg = "#d0bec8" }),
		DevIconObjectiveCPlusPlus({ fg = "#519aba" }),
		DevIconTsx({ fg = "#1354bf" }),
		DevIconJsx({ fg = "#20c2e3" }),
		DevIconGTK({ fg = "#ffffff" }),
		DevIconMakefile({ fg = "#6d8086" }),
		DevIconCache({ fg = "#ffffff" }),
		DevIconriver({ fg = "#000000" }),
		DevIconQtile({ fg = "#ffffff" }),
		DevIconJWM({ fg = "#0078cd" }),
		DevIconFluxbox({ fg = "#555555" }),
		DevIconHtm({ fg = "#e34c26" }),
		DevIconEnlightenment({ fg = "#ffffff" }),
		DevIconH({ fg = "#a074c4" }),
		DevIcondwm({ fg = "#1177aa" }),
		DevIconEx({ fg = "#a074c4" }),
		DevIconBSPWM({ fg = "#2f2f2f" }),
		DevIconHyprland({ fg = "#00aaae" }),
		DevIconawesome({ fg = "#535d6c" }),
		DevIconSRCINFO({ fg = "#0f94d2" }),
		DevIconBuildProps({ fg = "#00a2ff" }),
		DevIconBuildTargets({ fg = "#00a2ff" }),
		DevIconXauthority({ fg = "#e54d18" }),
		DevIconPackagesProps({ fg = "#00a2ff" }),
		DevIconXresources({ fg = "#e54d18" }),
		DevIconPrusaSlicer({ fg = "#ec6b23" }),
		DevIconFreeCADConfig({ fg = "#cb333b" }),
		DevIconAUTHORS({ fg = "#a172ff" }),
		DevIconCPlusPlus({ fg = "#f34b7d" }),
		DevIconUbuntu({ fg = "#dd4814" }),
		DevIconVoid({ fg = "#295340" }),
		DevIconJsonc({ fg = "#cbcb41" }),
		DevIconDb({ fg = "#dad8d8" }),
		DevIconPxd({ fg = "#5aa7e4" }),
		DevIconOpenBSD({ fg = "#f2ca30" }),
		DevIconTypoScript({ fg = "#ff8700" }),
		DevIconCMake({ fg = "#dce3eb" }),
		DevIconDefault({ fg = "#6d8086" }),
		DevIconGitlabCI({ fg = "#e24329" }),
		DevIconConfiguration({ fg = "#6d8086" }),
		DevIconSolidWorksAsm({ fg = "#839463" }),
		DevIconSvelte({ fg = "#ff3e00" }),
		DevIconASM({ fg = "#0071c5" }),
		DevIconXInitrc({ fg = "#e54d18" }),
		DevIconLess({ fg = "#563d7c" }),
		DevIconBlender({ fg = "#ea7600" }),
		DevIconObjectFile({ fg = "#9f0500" }),
		DevIconEslintrc({ fg = "#4b32c3" }),
		DevIconZsh({ fg = "#89e051" }),
		DevIconDll({ fg = "#4d2c0b" }),
		DevIconScss({ fg = "#f55385" }),
		DevIconOggVorbis({ fg = "#0075aa" }),
		DevIconSettingsJson({ fg = "#854cc7" }),
		DevIconPy({ fg = "#ffbc03" }),
		DevIconNobaraLinux({ fg = "#ffffff" }),
		DevIconAsciinema({ fg = "#fd971f" }),
		DevIconMOV({ fg = "#fd971f" }),
		DevIconParabolaGNULinuxLibre({ fg = "#797dac" }),
		DevIconTypoScriptSetup({ fg = "#ff8700" }),
		DevIconNPMrc({ fg = "#e8274b" }),
		DevIconFreeCAD({ fg = "#cb333b" }),
		DevIconBashProfile({ fg = "#89e051" }),
		DevIconFavicon({ fg = "#cbcb41" }),
		DevIconRmd({ fg = "#519aba" }),
		DevIconBz({ fg = "#eca517" }),
		DevIconHyprpaper({ fg = "#00aaae" }),
		DevIconHyprlock({ fg = "#00aaae" }),
		DevIconBin({ fg = "#9f0500" }),
		DevIconVlang({ fg = "#5d87bf" }),
		DevIconTypeScriptDeclaration({ fg = "#d59855" }),
		DevIconLibreOfficeCalc({ fg = "#78fc4e" }),
		DevIconSha256({ fg = "#8c86af" }),
		DevIconPhp({ fg = "#a074c4" }),
		DevIconEnv({ fg = "#faf743" }),
		DevIconBash({ fg = "#89e051" }),
		DevIconScala({ fg = "#cc3e44" }),
		DevIconTails({ fg = "#56347c" }),
		DevIconArch({ fg = "#0f94d2" }),
		DevIconMageia({ fg = "#2397d4" }),
		DevIconGruntfile({ fg = "#e37933" }),
		DevIconLXLE({ fg = "#474747" }),
		DevIconNswag({ fg = "#85ea2d" }),
		DevIconGif({ fg = "#a074c4" }),
		DevIconBabelrc({ fg = "#cbcb41" }),
		DevIconGulpfile({ fg = "#cc3e44" }),
		DevIconLeap({ fg = "#fbc75d" }),
		DevIconKali({ fg = "#2777ff" }),
		DevIconXlsx({ fg = "#207245" }),
		DevIconObjectiveC({ fg = "#599eff" }),
		DevIconXls({ fg = "#207245" }),
		DevIconPptx({ fg = "#cb4a32" }),
		DevIconTxz({ fg = "#eca517" }),
		DevIconPpt({ fg = "#cb4a32" }),
		DevIconGCode({ fg = "#1471ad" }),
		DevIconNixOS({ fg = "#7ab1db" }),
		DevIconAdaFile({ fg = "#599eff" }),
		DevIconHyperbolaGNULinuxLibre({ fg = "#c0c0c0" }),
		DevIconManjaro({ fg = "#33b959" }),
		DevIconDocx({ fg = "#185abd" }),
		DevIconJavaScriptReactTest({ fg = "#20c2e3" }),
		DevIconZst({ fg = "#eca517" }),
		DevIconXz({ fg = "#eca517" }),
		DevIconGentoo({ fg = "#b1abce" }),
		DevIconPyx({ fg = "#5aa7e4" }),
		DevIconFreeBSD({ fg = "#c90f02" }),
		DevIconGz({ fg = "#eca517" }),
		DevIconFedora({ fg = "#072a5e" }),
		DevIconBz2({ fg = "#eca517" }),
		DevIconDebian({ fg = "#a80030" }),
		DevIconWebp({ fg = "#a074c4" }),
		DevIconCantorrc({ fg = "#1c99f3" }),
		DevIconpostmarketOS({ fg = "#009900" }),
		DevIconBunLockfile({ fg = "#eadcd1" }),
		DevIconFdmdownload({ fg = "#44cda8" }),
		DevIconScheme({ fg = "#eeeeee" }),
		DevIconZigObjectNotation({ fg = "#f69a1b" }),
		DevIconsbt({ fg = "#cc3e44" }),
		DevIconSass({ fg = "#f55385" }),
		DevIcon7z({ fg = "#eca517" }),
		DevIconTerminal({ fg = "#31b53e" }),
		DevIconArcoLinux({ fg = "#6690eb" }),
		DevIconHTTP({ fg = "#008ec7" }),
		DevIconGleam({ fg = "#ffaff3" }),
		DevIconGvimrc({ fg = "#019833" }),
		DevIconNfo({ fg = "#ffffcd" }),
		DevIconKritarc({ fg = "#f245fb" }),
		DevIconGarudaLinux({ fg = "#2974e1" }),
		DevIconEpub({ fg = "#eab16d" }),
		DevIconTex({ fg = "#3d6117" }),
		DevIconEmbeddedOpenTypeFont({ fg = "#ececec" }),
		DevIconCsh({ fg = "#4d5a5e" }),
		DevIconElisp({ fg = "#8172be" }),
		DevIconKritadisplayrc({ fg = "#f245fb" }),
		DevIconDiff({ fg = "#41535b" }),
		DevIconElementary({ fg = "#5890c2" }),
		DevIconLogos({ fg = "#519aba" }),
		DevIconJson({ fg = "#cbcb41" }),
		DevIconVim({ fg = "#019833" }),
		DevIconMustache({ fg = "#e37933" }),
		DevIconMl({ fg = "#e37933" }),
		DevIconParrot({ fg = "#54deff" }),
		DevIconHpp({ fg = "#a074c4" }),
		DevIconEbook({ fg = "#eab16d" }),
		DevIconSlackware({ fg = "#475fa9" }),
		DevIconAutoCADDxf({ fg = "#839463" }),
		DevIconSharedObject({ fg = "#dcddd6" }),
		DevIconAutoCADDwg({ fg = "#839463" }),
		DevIconKsh({ fg = "#4d5a5e" }),
		DevIconLuaurc({ fg = "#00a2ff" }),
		DevIconXsession({ fg = "#e54d18" }),
		DevIconRobotsTxt({ fg = "#5d7096" }),
		DevIconLXDE({ fg = "#a4a4a4" }),
		DevIconVimrc({ fg = "#019833" }),
		DevIconMd5({ fg = "#8c86af" }),
		DevIconLinuxKernelObject({ fg = "#dcddd6" }),
		DevIconLua({ fg = "#51a0cf" }),
		DevIconSrt({ fg = "#ffb713" }),
		DevIconIonic({ fg = "#4f8ff7" }),
		DevIconLXQt({ fg = "#0191d2" }),
		DevIconXorgConf({ fg = "#e54d18" }),
		DevIconM3u({ fg = "#ed95ae" }),
		DevIconCMakeLists({ fg = "#dce3eb" }),
		DevIconFs({ fg = "#519aba" }),
		DevIconQuery({ fg = "#90a850" }),
		DevIconNano({ fg = "#440077" }),
		DevIconPrettierIgnore({ fg = "#4285f4" }),
		DevIconLXDEConfigFile({ fg = "#909090" }),
		DevIconMobi({ fg = "#eab16d" }),
		DevIconBashrc({ fg = "#89e051" }),
		DevIconPackedResource({ fg = "#6d8086" }),
		DevIconLibrecadFontFile({ fg = "#ececec" }),
		DevIconApp({ fg = "#9f0500" }),
		DevIconCheckhealth({ fg = "#75b4fb" }),
		DevIconapk({ fg = "#34a853" }),
		DevIconGradleBuildScript({ fg = "#005f87" }),
		DevIconD({ fg = "#b03931" }),
		DevIconCrdownload({ fg = "#44cda8" }),
		DevIconEslintIgnore({ fg = "#4b32c3" }),
		DevIconAudioInterchangeFileFormat({ fg = "#00afff" }),
		DevIconRar({ fg = "#eca517" }),
		DevIconKrita({ fg = "#f245fb" }),
		DevIconTor({ fg = "#519aba" }),
		DevIconDsStore({ fg = "#41535b" }),
		DevIconMdx({ fg = "#519aba" }),
		DevIconMonkeysAudio({ fg = "#00afff" }),
		DevIconKiCad({ fg = "#ffffff" }),
		DevIconNim({ fg = "#f3d400" }),
		DevIconKdenlive({ fg = "#83b8f2" }),
		DevIconDeepin({ fg = "#2ca7f8" }),
		DevIconKdbx({ fg = "#529b34" }),
		DevIconZorin({ fg = "#14a1e8" }),
		DevIconJpeg({ fg = "#a074c4" }),
		DevIconSlim({ fg = "#e34c26" }),
		DevIconKdb({ fg = "#529b34" }),
		DevIconXeroLinux({ fg = "#888fe2" }),
		DevIconKbx({ fg = "#737672" }),
		DevIconGoMod({ fg = "#00add8" }),
		DevIconStorybookJavaScript({ fg = "#ff4785" }),
		DevIconJpegXl({ fg = "#a074c4" }),
		DevIconKalgebrarc({ fg = "#1c99f3" }),
		DevIconVanillaOS({ fg = "#fabd4d" }),
		DevIconSlnx({ fg = "#854cc7" }),
		DevIconDockerIgnore({ fg = "#458ee6" }),
		DevIconTgz({ fg = "#eca517" }),
		DevIconTumbleweed({ fg = "#35b9ab" }),
		DevIconColdFusionTag({ fg = "#01a4ba" }),
		DevIconCodespell({ fg = "#35da60" }),
		DevIconTrisquelGNULinux({ fg = "#0f58b6" }),
		DevIconJustfile({ fg = "#6d8086" }),
		DevIconIxx({ fg = "#519aba" }),
		DevIconHypridle({ fg = "#00aaae" }),
		DevIconIso({ fg = "#d0bec8" }),
		DevIconPyLintConfig({ fg = "#6d8086" }),
		DevIconAdvancedAudioCoding({ fg = "#00afff" }),
		DevIconErb({ fg = "#701516" }),
		DevIconConfigRu({ fg = "#701516" }),
		DevIconGo({ fg = "#00add8" }),
		DevIconXpi({ fg = "#ff1b01" }),
		DevIconPsScriptfile({ fg = "#4273ca" }),
		DevIconPsScriptModulefile({ fg = "#6975c4" }),
		DevIconPsManifestfile({ fg = "#6975c4" }),
		DevIconSwift({ fg = "#e37933" }),
		DevIconImage({ fg = "#d0bec8" }),
		DevIconGitCommit({ fg = "#f54d27" }),
		DevIconIgs({ fg = "#839463" }),
		DevIconElm({ fg = "#519aba" }),
		DevIconIges({ fg = "#839463" }),
		DevIconLeex({ fg = "#a074c4" }),
		DevIconGitBlameIgnore({ fg = "#f54d27" }),
		DevIconIfc({ fg = "#839463" }),
		DevIconPKGBUILD({ fg = "#0f94d2" }),
		DevIconIfb({ fg = "#2b2e83" }),
		DevIconCSharpProject({ fg = "#512bd4" }),
		DevIconSte({ fg = "#839463" }),
		DevIconGIMP({ fg = "#635b46" }),
		DevIconAi({ fg = "#cbcb41" }),
		DevIconIcs({ fg = "#2b2e83" }),
		DevIconStep({ fg = "#839463" }),
		DevIconIge({ fg = "#839463" }),
		DevIconXaml({ fg = "#512bd4" }),
		sym("DevIconPy.typed")({ fg = "#ffbc03" }),
		DevIconIcal({ fg = "#2b2e83" }),
		DevIconStp({ fg = "#839463" }),
		DevIconXcLocalization({ fg = "#2596be" }),
		DevIconRasi({ fg = "#cbcb41" }),
		DevIconEdn({ fg = "#519aba" }),
		DevIconSh({ fg = "#4d5a5e" }),
		DevIconTailwindConfig({ fg = "#20c2e3" }),
		DevIconStaticLibraryArchive({ fg = "#dcddd6" }),
		DevIconPls({ fg = "#ed95ae" }),
		DevIconIco({ fg = "#cbcb41" }),
		DevIconSha384({ fg = "#8c86af" }),
		DevIconZip({ fg = "#eca517" }),
		DevIconConf({ fg = "#6d8086" }),
		DevIconHuff({ fg = "#4242c7" }),
		DevIconPackageJson({ fg = "#e8274b" }),
		DevIconIcalendar({ fg = "#2b2e83" }),
		DevIconPng({ fg = "#a074c4" }),
		DevIconRproj({ fg = "#358a5b" }),
		DevIconDoc({ fg = "#185abd" }),
		DevIconAstro({ fg = "#e23f67" }),
		DevIconBzl({ fg = "#89e051" }),
		DevIconBibTeX({ fg = "#cbcb41" }),
		DevIconHaxe({ fg = "#ea8220" }),
		DevIconWindowsMediaAudio({ fg = "#00afff" }),
		DevIconLuau({ fg = "#00a2ff" }),
		DevIconPrisma({ fg = "#5a67d8" }),
		DevIconEditorConfig({ fg = "#fff2f2" }),
		DevIconLibreOfficeFormula({ fg = "#ff5a96" }),
		DevIconInfo({ fg = "#ffffcd" }),
		DevIconKiCadFootprintTable({ fg = "#ffffff" }),
		DevIconPdf({ fg = "#b30b00" }),
		DevIconZig({ fg = "#f69a1b" }),
		DevIconToml({ fg = "#9c4221" }),
		DevIconTwig({ fg = "#8dc149" }),
		DevIconMpp({ fg = "#519aba" }),
		DevIconDownload({ fg = "#44cda8" }),
		DevIconGodotTextScene({ fg = "#6d8086" }),
		DevIconExe({ fg = "#9f0500" }),
		DevIconCss({ fg = "#663399" }),
		DevIconcuda({ fg = "#89e051" }),
		DevIconFeature({ fg = "#00a818" }),
		DevIconTFVars({ fg = "#5f43e9" }),
		DevIconBz3({ fg = "#eca517" }),
		DevIconNorg({ fg = "#4878be" }),
		DevIconClojureDart({ fg = "#519aba" }),
		DevIconMagnet({ fg = "#a51b16" }),
		DevIconBlade({ fg = "#f05340" }),
		DevIconOrgMode({ fg = "#77aa99" }),
		DevIconJpg({ fg = "#a074c4" }),
		DevIconFIGletFontControl({ fg = "#ececec" }),
		DevIconFIGletFontFormat({ fg = "#ececec" }),
		DevIconRakefile({ fg = "#701516" }),
		DevIconGNOME({ fg = "#ffffff" }),
		DevIconKDEPlasma({ fg = "#1b89f4" }),
		DevIconAss({ fg = "#ffb713" }),
		DevIconSsa({ fg = "#ffb713" }),
		DevIconLib({ fg = "#4d2c0b" }),
		DevIconXfce({ fg = "#00aadf" }),
		DevIconMATE({ fg = "#9bda5c" }),
		DevIconIndexTheme({ fg = "#2db96f" }),
		DevIconOpenSCAD({ fg = "#f9d72c" }),
		DevIconUI({ fg = "#015bf0" }),
		DevIconCxxm({ fg = "#519aba" }),
		DevIconCppm({ fg = "#519aba" }),
		DevIconCPlusPlusModule({ fg = "#f34b7d" }),
		DevIconMarkdown({ fg = "#dddddd" }),
		DevIconHxx({ fg = "#a074c4" }),
		DevIconI18nConfig({ fg = "#7986cb" }),
		DevIconCxx({ fg = "#519aba" }),
		DevIconRedhat({ fg = "#ee0000" }),
		DevIconImportConfiguration({ fg = "#ececec" }),
		DevIconHh({ fg = "#a074c4" }),
		DevIconProlog({ fg = "#e4b854" }),
		DevIconPatch({ fg = "#41535b" }),
		DevIconHyprlandd({ fg = "#00aaae" }),
		DevIconRs({ fg = "#dea584" }),
		DevIconRake({ fg = "#701516" }),
		DevIconGemspec({ fg = "#701516" }),
		DevIconSln({ fg = "#854cc7" }),
		DevIconCentos({ fg = "#a2518d" }),
		DevIconCs({ fg = "#596706" }),
		DevIconSml({ fg = "#e37933" }),
		DevIconRaspberryPiOS({ fg = "#be1848" }),
		DevIconSabayon({ fg = "#c6c6c6" }),
		DevIconClojureJS({ fg = "#519aba" }),
		DevIconClojureC({ fg = "#8dc149" }),
		DevIconClojure({ fg = "#8dc149" }),
		DevIconSolidity({ fg = "#519aba" }),
		DevIconMXLinux({ fg = "#ffffff" }),
		DevIconGradleWrapperScript({ fg = "#005f87" }),
		DevIconDrools({ fg = "#ffafaf" }),
		DevIconGradleProperties({ fg = "#005f87" }),
		DevIconOggMultiplex({ fg = "#fd971f" }),
		DevIconGradleWrapperProperties({ fg = "#005f87" }),
		DevIconFusion360({ fg = "#839463" }),
		DevIconAdaSpecification({ fg = "#a074c4" }),
		DevIconWaveformAudioFile({ fg = "#00afff" }),
		DevIconNushell({ fg = "#3aa675" }),
		DevIconMPEGAudioLayerIII({ fg = "#00afff" }),
		DevIconMPEG4({ fg = "#00afff" }),
		DevIconFreeLosslessAudioCodec({ fg = "#0075aa" }),
		DevIconKiCadCache({ fg = "#ffffff" }),
		DevIconColdFusionScript({ fg = "#01a4ba" }),
		DevIconWindowsMediaVideo({ fg = "#fd971f" }),
		DevIconBmp({ fg = "#a074c4" }),
		DevIconWebm({ fg = "#fd971f" }),
		DevIconDconf({ fg = "#ffffff" }),
		DevIconMp4({ fg = "#fd971f" }),
		DevIconMkv({ fg = "#fd971f" }),
		DevIconM4V({ fg = "#fd971f" }),
		DevIconVue({ fg = "#8dc149" }),
		DevIcon3gp({ fg = "#fd971f" }),
		DevIconCowsayFile({ fg = "#965824" }),
		DevIconBazel({ fg = "#89e051" }),
		DevIconLrc({ fg = "#ffb713" }),
		DevIconWindows({ fg = "#00a4ef" }),
		DevIconBlueprint({ fg = "#5796e2" }),
		DevIconPreCommitConfig({ fg = "#f8b424" }),
		DevIconVala({ fg = "#7b3db9" }),
		DevIconReScriptInterface({ fg = "#f55385" }),
		DevIconReScript({ fg = "#cc3e44" }),
		DevIconnode({ fg = "#5fa04e" }),
		DevIconMailmap({ fg = "#f54d27" }),
		lualine_x_filetype_DevIconDefault_normal({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_insert({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_visual({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_replace({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_command({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_terminal({ bg = "#112638", fg = "#6d8086", gui = "nocombine" }),
		lualine_x_filetype_DevIconDefault_inactive({ bg = "#2c3043", fg = "#6d8086", gui = "nocombine" }),
		lualine_transitional_lualine_a_normal_to_lualine_b_normal({ bg = "#9abbe6", fg = "#2979ff", gui = "nocombine" }),
		lualine_transitional_lualine_b_normal_to_lualine_c_normal({ bg = "#112638", fg = "#9abbe6", gui = "nocombine" }),
		TodoBgWARN({ bg = "#ffc777", fg = "#000000", gui = "bold" }),
		TodoFgWARN({ fg = "#ffc777" }),
		TodoSignWARN({ fg = "#ffc777" }),
		TodoBgNOTE({ bg = "#009955", fg = "#000000", gui = "bold" }),
		TodoFgNOTE({ fg = "#009955" }),
		TodoSignNOTE({ fg = "#009955" }),
		TodoBgHACK({ bg = "#ffc777", fg = "#000000", gui = "bold" }),
		TodoFgHACK({ fg = "#ffc777" }),
		TodoSignHACK({ fg = "#ffc777" }),
		TodoBgPERF({ bg = "#c099ff", fg = "#000000", gui = "bold" }),
		TodoFgPERF({ fg = "#c099ff" }),
		TodoSignPERF({ fg = "#c099ff" }),
		TodoBgTODO({ bg = "#0db9d7", fg = "#000000", gui = "bold" }),
		TodoFgTODO({ fg = "#0db9d7" }),
		TodoSignTODO({ fg = "#0db9d7" }),
		TodoBgTEST({ bg = "#c099ff", fg = "#000000", gui = "bold" }),
		TodoFgTEST({ fg = "#c099ff" }),
		TodoSignTEST({ fg = "#c099ff" }),
		TodoBgFIX({ bg = "#c53b53", fg = "#000000", gui = "bold" }),
		TodoFgFIX({ fg = "#c53b53" }),
		TodoSignFIX({ fg = "#c53b53" }),
		lualine_x_filetype_DevIconLua_normal({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_insert({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_visual({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_replace({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_command({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_terminal({ bg = "#112638", fg = "#51a0cf", gui = "nocombine" }),
		lualine_x_filetype_DevIconLua_inactive({ bg = "#2c3043", fg = "#51a0cf", gui = "nocombine" }),
		PHinfo({ fg = "#4fc1ff" }),
		PHwarning({ fg = "#fbbf24" }),
		PHerror({ fg = "#dc2626" }),
		lualine_transitional_lualine_a_command_to_lualine_b_command({
			bg = "#76ff03",
			fg = "#ffda7b",
			gui = "nocombine",
		}),
		lualine_transitional_lualine_b_command_to_lualine_c_command({
			bg = "#112638",
			fg = "#76ff03",
			gui = "nocombine",
		}),
		BlinkCmpCursorLineMenuHack({ bg = "#363c58" }),
	}
end)
return theme
