local colors = {
	Normal = { fg = "#c8d3f5" },
	Ignore = { link = "Normal" },
	LspKindFile = { link = "Normal" },
	NvimSpacing = { link = "Normal" },
	Added = { fg = "nvimlightgreen" },
	BlinkCmpCursorLineMenuHack = { bg = "#363c58" },
	BlinkCmpDoc = { fg = "#a0c0d0", bg = "#1a1a22" },
	BlinkCmpDocBorder = { fg = "#1a1a22", bg = "#1a1a22" },
	BlinkCmpGhostText = { fg = "#444a73" },
	BlinkCmpKindCodeium = { fg = "#4fd6be" },
	BlinkCmpKindCopilot = { fg = "#4fd6be" },
	BlinkCmpKindDefault = { fg = "#828bb8" },
	BlinkCmpKindSupermaven = { fg = "#4fd6be" },
	BlinkCmpKindTabNine = { fg = "#4fd6be" },
	BlinkCmpLabel = { fg = "#c8d3f5" },
	BlinkCmpLabelDeprecated = { fg = "#3b4261", strikethrough = true },
	BlinkCmpLabelMatch = { fg = "#c586c0", bold = true },
	BlinkCmpMenu = { fg = "#a0c0d0", bg = "#0f0f14" },
	BlinkCmpMenuBorder = { fg = "#a0c0d0", bg = "#0f0f14" },
	BlinkCmpSignatureHelp = { fg = "#c8d3f5", bg = "#1e2030" },
	BlinkCmpSignatureHelpBorder = { fg = "#589ed7", bg = "#1e2030" },
	Bold = { fg = "#c8d3f5", bold = true },
	Changed = { fg = "nvimlightcyan" },
	Character = { fg = "#c3e88d" },
	["@character"] = { link = "Character" },
	CmpDoc = { fg = "#a0c0d0", bg = "#05050a" },
	CmpDocBorder = { fg = "#05050a", bg = "#05050a" },
	CmpItemAbbr = { fg = "#a0c0d0" },
	CmpItemAbbrMatch = { fg = "#c586c0", bold = true },
	CmpItemKind = { fg = "#7fd1e0" },
	CmpItemKindClass = { fg = "#80d4a0" },
	CmpItemKindEnum = { fg = "#80d4a0" },
	CmpItemKindField = { fg = "#ffc66d" },
	CmpItemKindFunction = { fg = "#a0c0d0" },
	CmpItemKindInterface = { fg = "#7fd1e0" },
	CmpItemKindKeyword = { fg = "#c586c0" },
	CmpItemKindMethod = { fg = "#a0c0d0" },
	CmpItemKindProperty = { fg = "#c586c0" },
	CmpItemKindSnippet = { fg = "#a0c0d0" },
	CmpItemKindText = { fg = "#a0c0d0" },
	CmpItemKindVariable = { fg = "#ffc66d" },
	CmpItemMenu = { fg = "#607080" },
	CmpPmenu = { fg = "#a0c0d0", bg = "#07070f" },
	CmpPmenuBorder = { fg = "#07070f", bg = "#07070f" },
	CmpPmenuSbar = { bg = "#0a0a10" },
	CmpPmenuSel = { fg = "#ffffff", bg = "#252530" },
	CmpPmenuThumb = { bg = "#4a4a4a" },
	ColorColumn = { bg = "#1b1d2b" },
	Comment = { fg = "#636da6", italic = true },
	MiniDepsPlaceholder = { link = "Comment" },
	MiniDepsTitleSame = { link = "Comment" },
	MiniJump2dDim = { link = "Comment" },
	OilHidden = { link = "Comment" },
	OilLinkTarget = { link = "Comment" },
	OilTrashSourcePath = { link = "Comment" },
	luaComment = { link = "Comment" },
	["@comment"] = { link = "Comment" },
	Conceal = { fg = "#737aa2" },
	LspKindSnippet = { link = "Conceal" },
	Constant = { fg = "#ff966c" },
	Boolean = { link = "Constant" },
	Number = { link = "Constant" },
	TelescopePreviewBlock = { link = "Constant" },
	TelescopePreviewCharDev = { link = "Constant" },
	TelescopePreviewGroup = { link = "Constant" },
	TelescopePreviewPipe = { link = "Constant" },
	TelescopePreviewRead = { link = "Constant" },
	TelescopePreviewUser = { link = "Constant" },
	TelescopeResultsConstant = { link = "Constant" },
	luaConstant = { link = "Constant" },
	["@constant"] = { link = "Constant" },
	Cursor = { fg = "#222436", bg = "#c8d3f5" },
	CursorColumn = { bg = "#2f334d" },
	CursorIM = { fg = "#222436", bg = "#c8d3f5" },
	CursorLine = { bg = "#2f334d" },
	MiniFilesCursorLine = { link = "CursorLine" },
	MiniPickMatchCurrent = { link = "CursorLine" },
	MiniPickPreviewLine = { link = "CursorLine" },
	CursorLineNr = { fg = "#ff966c", bold = true },
	Debug = { fg = "#ff966c" },
	["@keyword.debug"] = { link = "Debug" },
	DevIcon3DObjectFile = { fg = "#888888" },
	DevIcon3gp = { fg = "#fd971f" },
	DevIcon7z = { fg = "#eca517" },
	DevIconAOSC = { fg = "#c00000" },
	DevIconAPL = { fg = "#24a148" },
	DevIconASM = { fg = "#0071c5" },
	DevIconAUTHORS = { fg = "#a172ff" },
	DevIconAdaBody = { fg = "#599eff" },
	DevIconAdaFile = { fg = "#599eff" },
	DevIconAdaSpecification = { fg = "#a074c4" },
	DevIconAdvancedAudioCoding = { fg = "#00afff" },
	DevIconAi = { fg = "#cbcb41" },
	DevIconAlmalinux = { fg = "#ff4649" },
	DevIconAlpine = { fg = "#0d597f" },
	DevIconAndroid = { fg = "#34a853" },
	DevIconApp = { fg = "#9f0500" },
	DevIconApple = { fg = "#a2aaad" },
	DevIconAppleScript = { fg = "#6d8085" },
	DevIconArch = { fg = "#0f94d2" },
	DevIconArchcraft = { fg = "#86bba3" },
	DevIconArchlabs = { fg = "#503f42" },
	DevIconArcoLinux = { fg = "#6690eb" },
	DevIconArduino = { fg = "#56b6c2" },
	DevIconArtix = { fg = "#41b4d7" },
	DevIconAsc = { fg = "#576d7f" },
	DevIconAsciinema = { fg = "#fd971f" },
	DevIconAss = { fg = "#ffb713" },
	DevIconAstro = { fg = "#e23f67" },
	DevIconAudioInterchangeFileFormat = { fg = "#00afff" },
	DevIconAutoCADDwg = { fg = "#839463" },
	DevIconAutoCADDxf = { fg = "#839463" },
	DevIconAvif = { fg = "#a074c4" },
	DevIconAwk = { fg = "#4d5a5e" },
	DevIconAzureCli = { fg = "#0078d4" },
	DevIconBSPWM = { fg = "#2f2f2f" },
	DevIconBabelrc = { fg = "#cbcb41" },
	DevIconBackup = { fg = "#6d8086" },
	DevIconBash = { fg = "#89e051" },
	DevIconBashProfile = { fg = "#89e051" },
	DevIconBashrc = { fg = "#89e051" },
	DevIconBat = { fg = "#c1f12e" },
	DevIconBazel = { fg = "#89e051" },
	DevIconBazelBuild = { fg = "#89e051" },
	DevIconBazelWorkspace = { fg = "#89e051" },
	DevIconBibTeX = { fg = "#cbcb41" },
	DevIconBicep = { fg = "#519aba" },
	DevIconBicepParameters = { fg = "#9f74b3" },
	DevIconBigLinux = { fg = "#189fc8" },
	DevIconBin = { fg = "#9f0500" },
	DevIconBinaryGLTF = { fg = "#ffb13b" },
	DevIconBlade = { fg = "#f05340" },
	DevIconBlender = { fg = "#ea7600" },
	DevIconBlueprint = { fg = "#5796e2" },
	DevIconBmp = { fg = "#a074c4" },
	DevIconBoundaryRepresentation = { fg = "#839463" },
	DevIconBrewfile = { fg = "#701516" },
	DevIconBudgie = { fg = "#4e5361" },
	DevIconBuildProps = { fg = "#00a2ff" },
	DevIconBuildTargets = { fg = "#00a2ff" },
	DevIconBunLockfile = { fg = "#eadcd1" },
	DevIconBz = { fg = "#eca517" },
	DevIconBz2 = { fg = "#eca517" },
	DevIconBz3 = { fg = "#eca517" },
	DevIconBzl = { fg = "#89e051" },
	DevIconC = { fg = "#599eff" },
	DevIconCMake = { fg = "#dce3eb" },
	DevIconCMakeLists = { fg = "#dce3eb" },
	DevIconCPlusPlus = { fg = "#f34b7d" },
	DevIconCPlusPlusModule = { fg = "#f34b7d" },
	DevIconCSharpProject = { fg = "#512bd4" },
	DevIconCache = { fg = "#ffffff" },
	DevIconCantorrc = { fg = "#1c99f3" },
	DevIconCentos = { fg = "#a2518d" },
	DevIconCheckhealth = { fg = "#75b4fb" },
	DevIconCinnamon = { fg = "#dc682e" },
	DevIconCjs = { fg = "#cbcb41" },
	DevIconClangConfig = { fg = "#6d8086" },
	DevIconClojure = { fg = "#8dc149" },
	DevIconClojureC = { fg = "#8dc149" },
	DevIconClojureDart = { fg = "#519aba" },
	DevIconClojureJS = { fg = "#519aba" },
	DevIconCobol = { fg = "#005ca5" },
	DevIconCodeOfConduct = { fg = "#e41662" },
	DevIconCodespell = { fg = "#35da60" },
	DevIconCoffee = { fg = "#cbcb41" },
	DevIconColdFusionScript = { fg = "#01a4ba" },
	DevIconColdFusionTag = { fg = "#01a4ba" },
	DevIconCommitlintConfig = { fg = "#2b9689" },
	DevIconConda = { fg = "#43b02a" },
	DevIconConf = { fg = "#6d8086" },
	DevIconConfig = { fg = "#6d8086" },
	DevIconConfigRu = { fg = "#701516" },
	DevIconConfiguration = { fg = "#6d8086" },
	DevIconCowsayFile = { fg = "#965824" },
	DevIconCp = { fg = "#519aba" },
	DevIconCpp = { fg = "#519aba" },
	DevIconCppm = { fg = "#519aba" },
	DevIconCrdownload = { fg = "#44cda8" },
	DevIconCrystal = { fg = "#c8c8c8" },
	DevIconCrystalLinux = { fg = "#a900ff" },
	DevIconCs = { fg = "#596706" },
	DevIconCsh = { fg = "#4d5a5e" },
	DevIconCson = { fg = "#cbcb41" },
	DevIconCss = { fg = "#663399" },
	DevIconCsv = { fg = "#89e051" },
	DevIconCts = { fg = "#519aba" },
	DevIconCue = { fg = "#ed95ae" },
	DevIconCxx = { fg = "#519aba" },
	DevIconCxxm = { fg = "#519aba" },
	DevIconD = { fg = "#b03931" },
	DevIconDart = { fg = "#03589c" },
	DevIconDb = { fg = "#dad8d8" },
	DevIconDconf = { fg = "#ffffff" },
	DevIconDebian = { fg = "#a80030" },
	DevIconDeepin = { fg = "#2ca7f8" },
	DevIconDefault = { fg = "#6d8086" },
	DevIconDesktopEntry = { fg = "#563d7c" },
	DevIconDevuan = { fg = "#404a52" },
	DevIconDiff = { fg = "#41535b" },
	DevIconDll = { fg = "#4d2c0b" },
	DevIconDoc = { fg = "#185abd" },
	DevIconDockerIgnore = { fg = "#458ee6" },
	DevIconDockerfile = { fg = "#458ee6" },
	DevIconDocx = { fg = "#185abd" },
	DevIconDot = { fg = "#30638e" },
	DevIconDownload = { fg = "#44cda8" },
	DevIconDrools = { fg = "#ffafaf" },
	DevIconDropbox = { fg = "#0061fe" },
	DevIconDsStore = { fg = "#41535b" },
	DevIconDump = { fg = "#dad8d8" },
	DevIconEbook = { fg = "#eab16d" },
	DevIconEditorConfig = { fg = "#fff2f2" },
	DevIconEdn = { fg = "#519aba" },
	DevIconEex = { fg = "#a074c4" },
	DevIconEjs = { fg = "#cbcb41" },
	DevIconElementary = { fg = "#5890c2" },
	DevIconElf = { fg = "#9f0500" },
	DevIconElisp = { fg = "#8172be" },
	DevIconElm = { fg = "#519aba" },
	DevIconEmbeddedOpenTypeFont = { fg = "#ececec" },
	DevIconEndeavour = { fg = "#7b3db9" },
	DevIconEnlightenment = { fg = "#ffffff" },
	DevIconEnv = { fg = "#faf743" },
	DevIconEpp = { fg = "#ffa61a" },
	DevIconEpub = { fg = "#eab16d" },
	DevIconErb = { fg = "#701516" },
	DevIconErl = { fg = "#b83998" },
	DevIconEslintIgnore = { fg = "#4b32c3" },
	DevIconEslintrc = { fg = "#4b32c3" },
	DevIconEx = { fg = "#a074c4" },
	DevIconExe = { fg = "#9f0500" },
	DevIconExs = { fg = "#a074c4" },
	DevIconFIGletFontControl = { fg = "#ececec" },
	DevIconFIGletFontFormat = { fg = "#ececec" },
	DevIconFavicon = { fg = "#cbcb41" },
	DevIconFdmdownload = { fg = "#44cda8" },
	DevIconFeature = { fg = "#00a818" },
	DevIconFedora = { fg = "#072a5e" },
	DevIconFennel = { fg = "#fff3d7" },
	DevIconFish = { fg = "#4d5a5e" },
	DevIconFluxbox = { fg = "#555555" },
	DevIconFortran = { fg = "#734f96" },
	DevIconFreeBSD = { fg = "#c90f02" },
	DevIconFreeCAD = { fg = "#cb333b" },
	DevIconFreeCADConfig = { fg = "#cb333b" },
	DevIconFreeLosslessAudioCodec = { fg = "#0075aa" },
	DevIconFs = { fg = "#519aba" },
	DevIconFsharp = { fg = "#519aba" },
	DevIconFsi = { fg = "#519aba" },
	DevIconFsscript = { fg = "#519aba" },
	DevIconFsx = { fg = "#519aba" },
	DevIconFusion360 = { fg = "#839463" },
	DevIconGCode = { fg = "#1471ad" },
	DevIconGDScript = { fg = "#6d8086" },
	DevIconGIMP = { fg = "#635b46" },
	DevIconGNOME = { fg = "#ffffff" },
	DevIconGPRBuildProject = { fg = "#6d8086" },
	DevIconGTK = { fg = "#ffffff" },
	DevIconGarudaLinux = { fg = "#2974e1" },
	DevIconGemfile = { fg = "#701516" },
	DevIconGemspec = { fg = "#701516" },
	DevIconGentoo = { fg = "#b1abce" },
	DevIconGentooBuild = { fg = "#4c416e" },
	DevIconGif = { fg = "#a074c4" },
	DevIconGitAttributes = { fg = "#f54d27" },
	DevIconGitBlameIgnore = { fg = "#f54d27" },
	DevIconGitCommit = { fg = "#f54d27" },
	DevIconGitConfig = { fg = "#f54d27" },
	DevIconGitIgnore = { fg = "#f54d27" },
	DevIconGitLogo = { fg = "#f14c28" },
	DevIconGitModules = { fg = "#f54d27" },
	DevIconGitlabCI = { fg = "#e24329" },
	DevIconGleam = { fg = "#ffaff3" },
	DevIconGo = { fg = "#00add8" },
	DevIconGoMod = { fg = "#00add8" },
	DevIconGoSum = { fg = "#00add8" },
	DevIconGoWork = { fg = "#00add8" },
	DevIconGodotProject = { fg = "#6d8086" },
	DevIconGodotTextResource = { fg = "#6d8086" },
	DevIconGodotTextScene = { fg = "#6d8086" },
	DevIconGradle = { fg = "#005f87" },
	DevIconGradleBuildScript = { fg = "#005f87" },
	DevIconGradleProperties = { fg = "#005f87" },
	DevIconGradleSettings = { fg = "#005f87" },
	DevIconGradleWrapperProperties = { fg = "#005f87" },
	DevIconGradleWrapperScript = { fg = "#005f87" },
	DevIconGraphQL = { fg = "#e535ab" },
	DevIconGroovy = { fg = "#4a687c" },
	DevIconGruntfile = { fg = "#e37933" },
	DevIconGuix = { fg = "#ffcc00" },
	DevIconGulpfile = { fg = "#cc3e44" },
	DevIconGv = { fg = "#30638e" },
	DevIconGvimrc = { fg = "#019833" },
	DevIconGz = { fg = "#eca517" },
	DevIconH = { fg = "#a074c4" },
	DevIconHTTP = { fg = "#008ec7" },
	DevIconHaml = { fg = "#eaeae1" },
	DevIconHaxe = { fg = "#ea8220" },
	DevIconHbs = { fg = "#f0772b" },
	DevIconHeex = { fg = "#a074c4" },
	DevIconHexadecimal = { fg = "#2e63ff" },
	DevIconHh = { fg = "#a074c4" },
	DevIconHpp = { fg = "#a074c4" },
	DevIconHrl = { fg = "#b83998" },
	DevIconHs = { fg = "#a074c4" },
	DevIconHtm = { fg = "#e34c26" },
	DevIconHtml = { fg = "#e44d26" },
	DevIconHuff = { fg = "#4242c7" },
	DevIconHurl = { fg = "#ff0288" },
	DevIconHxx = { fg = "#a074c4" },
	DevIconHyperbolaGNULinuxLibre = { fg = "#c0c0c0" },
	DevIconHypridle = { fg = "#00aaae" },
	DevIconHyprland = { fg = "#00aaae" },
	DevIconHyprlandd = { fg = "#00aaae" },
	DevIconHyprlock = { fg = "#00aaae" },
	DevIconHyprpaper = { fg = "#00aaae" },
	DevIconI18nConfig = { fg = "#7986cb" },
	DevIconIcal = { fg = "#2b2e83" },
	DevIconIcalendar = { fg = "#2b2e83" },
	DevIconIco = { fg = "#cbcb41" },
	DevIconIcs = { fg = "#2b2e83" },
	DevIconIfb = { fg = "#2b2e83" },
	DevIconIfc = { fg = "#839463" },
	DevIconIge = { fg = "#839463" },
	DevIconIges = { fg = "#839463" },
	DevIconIgs = { fg = "#839463" },
	DevIconIllumos = { fg = "#ff430f" },
	DevIconImage = { fg = "#d0bec8" },
	DevIconImg = { fg = "#d0bec8" },
	DevIconImportConfiguration = { fg = "#ececec" },
	DevIconIndexTheme = { fg = "#2db96f" },
	DevIconInfo = { fg = "#ffffcd" },
	DevIconIni = { fg = "#6d8086" },
	DevIconIonic = { fg = "#4f8ff7" },
	DevIconIso = { fg = "#d0bec8" },
	DevIconIxx = { fg = "#519aba" },
	DevIconJWM = { fg = "#0078cd" },
	DevIconJava = { fg = "#cc3e44" },
	DevIconJavaScriptReactSpec = { fg = "#20c2e3" },
	DevIconJavaScriptReactTest = { fg = "#20c2e3" },
	DevIconJl = { fg = "#a270ba" },
	DevIconJpeg = { fg = "#a074c4" },
	DevIconJpegXl = { fg = "#a074c4" },
	DevIconJpg = { fg = "#a074c4" },
	DevIconJs = { fg = "#cbcb41" },
	DevIconJson = { fg = "#cbcb41" },
	DevIconJson5 = { fg = "#cbcb41" },
	DevIconJsonc = { fg = "#cbcb41" },
	DevIconJsx = { fg = "#20c2e3" },
	DevIconJustfile = { fg = "#6d8086" },
	DevIconKDEPlasma = { fg = "#1b89f4" },
	DevIconKDEglobals = { fg = "#1c99f3" },
	DevIconKDEneon = { fg = "#20a6a4" },
	DevIconKalgebrarc = { fg = "#1c99f3" },
	DevIconKali = { fg = "#2777ff" },
	DevIconKbx = { fg = "#737672" },
	DevIconKdb = { fg = "#529b34" },
	DevIconKdbx = { fg = "#529b34" },
	DevIconKdenlive = { fg = "#83b8f2" },
	DevIconKdenliveLayoutsrc = { fg = "#83b8f2" },
	DevIconKdenliverc = { fg = "#83b8f2" },
	DevIconKiCad = { fg = "#ffffff" },
	DevIconKiCadCache = { fg = "#ffffff" },
	DevIconKiCadFootprintTable = { fg = "#ffffff" },
	DevIconKiCadSymbolTable = { fg = "#ffffff" },
	DevIconKotlin = { fg = "#7f52ff" },
	DevIconKotlinScript = { fg = "#7f52ff" },
	DevIconKrita = { fg = "#f245fb" },
	DevIconKritadisplayrc = { fg = "#f245fb" },
	DevIconKritarc = { fg = "#f245fb" },
	DevIconKsh = { fg = "#4d5a5e" },
	DevIconKubuntu = { fg = "#007ac2" },
	DevIconLXDE = { fg = "#a4a4a4" },
	DevIconLXDEConfigFile = { fg = "#909090" },
	DevIconLXLE = { fg = "#474747" },
	DevIconLXQt = { fg = "#0191d2" },
	DevIconLXQtConfigFile = { fg = "#0192d3" },
	DevIconLabView = { fg = "#fec60a" },
	DevIconLeap = { fg = "#fbc75d" },
	DevIconLeex = { fg = "#a074c4" },
	DevIconLess = { fg = "#563d7c" },
	DevIconLhs = { fg = "#a074c4" },
	DevIconLib = { fg = "#4d2c0b" },
	DevIconLibreOfficeCalc = { fg = "#78fc4e" },
	DevIconLibreOfficeFormula = { fg = "#ff5a96" },
	DevIconLibreOfficeGraphics = { fg = "#fffb57" },
	DevIconLibreOfficeImpress = { fg = "#fe9c45" },
	DevIconLibreOfficeWriter = { fg = "#2dcbfd" },
	DevIconLibrecadFontFile = { fg = "#ececec" },
	DevIconLicense = { fg = "#d0bf41" },
	DevIconLinux = { fg = "#fdfdfb" },
	DevIconLinuxKernelObject = { fg = "#dcddd6" },
	DevIconLiquid = { fg = "#95bf47" },
	DevIconLocOS = { fg = "#fab402" },
	DevIconLocalization = { fg = "#2596be" },
	DevIconLock = { fg = "#bbbbbb" },
	DevIconLog = { fg = "#dddddd" },
	DevIconLogos = { fg = "#519aba" },
	DevIconLrc = { fg = "#ffb713" },
	DevIconLua = { fg = "#51a0cf" },
	DevIconLuau = { fg = "#00a2ff" },
	DevIconLuaurc = { fg = "#00a2ff" },
	DevIconM3u = { fg = "#ed95ae" },
	DevIconM3u8 = { fg = "#ed95ae" },
	DevIconM4V = { fg = "#fd971f" },
	DevIconMATE = { fg = "#9bda5c" },
	DevIconMOV = { fg = "#fd971f" },
	DevIconMPEG4 = { fg = "#00afff" },
	DevIconMPEGAudioLayerIII = { fg = "#00afff" },
	DevIconMXLinux = { fg = "#ffffff" },
	DevIconMageia = { fg = "#2397d4" },
	DevIconMagnet = { fg = "#a51b16" },
	DevIconMailmap = { fg = "#f54d27" },
	DevIconMakefile = { fg = "#6d8086" },
	DevIconManjaro = { fg = "#33b959" },
	DevIconMarkdown = { fg = "#dddddd" },
	DevIconMaterial = { fg = "#b83998" },
	DevIconMaven = { fg = "#7a0d21" },
	DevIconMd = { fg = "#dddddd" },
	DevIconMd5 = { fg = "#8c86af" },
	DevIconMdx = { fg = "#519aba" },
	DevIconMint = { fg = "#87c095" },
	DevIconMixLock = { fg = "#a074c4" },
	DevIconMjs = { fg = "#f1e05a" },
	DevIconMkv = { fg = "#fd971f" },
	DevIconMl = { fg = "#e37933" },
	DevIconMli = { fg = "#e37933" },
	DevIconMobi = { fg = "#eab16d" },
	DevIconMojo = { fg = "#ff4c1f" },
	DevIconMonkeysAudio = { fg = "#00afff" },
	DevIconMotoko = { fg = "#9772fb" },
	DevIconMp4 = { fg = "#fd971f" },
	DevIconMpp = { fg = "#519aba" },
	DevIconMpv = { fg = "#3b1342" },
	DevIconMts = { fg = "#519aba" },
	DevIconMustache = { fg = "#e37933" },
	DevIconNPMIgnore = { fg = "#e8274b" },
	DevIconNPMrc = { fg = "#e8274b" },
	DevIconNano = { fg = "#440077" },
	DevIconNfo = { fg = "#ffffcd" },
	DevIconNim = { fg = "#f3d400" },
	DevIconNix = { fg = "#7ebae4" },
	DevIconNixOS = { fg = "#7ab1db" },
	DevIconNobaraLinux = { fg = "#ffffff" },
	DevIconNodeModules = { fg = "#e8274b" },
	DevIconNorg = { fg = "#4878be" },
	DevIconNotebook = { fg = "#f57d01" },
	DevIconNswag = { fg = "#85ea2d" },
	DevIconNushell = { fg = "#3aa675" },
	DevIconNuxtConfig = { fg = "#00c58e" },
	DevIconObjectFile = { fg = "#9f0500" },
	DevIconObjectiveC = { fg = "#599eff" },
	DevIconObjectiveCPlusPlus = { fg = "#519aba" },
	DevIconOdin = { fg = "#3882d2" },
	DevIconOggMultiplex = { fg = "#fd971f" },
	DevIconOggSpeexAudio = { fg = "#0075aa" },
	DevIconOggVideo = { fg = "#fd971f" },
	DevIconOggVorbis = { fg = "#0075aa" },
	DevIconOpenBSD = { fg = "#f2ca30" },
	DevIconOpenSCAD = { fg = "#f9d72c" },
	DevIconOpenTypeFont = { fg = "#ececec" },
	DevIconOpusAudioFile = { fg = "#0075aa" },
	DevIconOrgMode = { fg = "#77aa99" },
	DevIconOut = { fg = "#9f0500" },
	DevIconPKGBUILD = { fg = "#0f94d2" },
	DevIconPackageJson = { fg = "#e8274b" },
	DevIconPackageLockJson = { fg = "#7a0d21" },
	DevIconPackagesProps = { fg = "#00a2ff" },
	DevIconPackedResource = { fg = "#6d8086" },
	DevIconParabolaGNULinuxLibre = { fg = "#797dac" },
	DevIconParrot = { fg = "#54deff" },
	DevIconPart = { fg = "#44cda8" },
	DevIconPatch = { fg = "#41535b" },
	DevIconPdf = { fg = "#b30b00" },
	DevIconPhp = { fg = "#a074c4" },
	DevIconPl = { fg = "#519aba" },
	DevIconPlatformio = { fg = "#f6822b" },
	DevIconPls = { fg = "#ed95ae" },
	DevIconPm = { fg = "#519aba" },
	DevIconPng = { fg = "#a074c4" },
	["DevIconPop_OS"] = { fg = "#48b9c7" },
	DevIconPp = { fg = "#ffa61a" },
	DevIconPpt = { fg = "#cb4a32" },
	DevIconPptx = { fg = "#cb4a32" },
	DevIconPreCommitConfig = { fg = "#f8b424" },
	DevIconPrettierConfig = { fg = "#4285f4" },
	DevIconPrettierIgnore = { fg = "#4285f4" },
	DevIconPrisma = { fg = "#5a67d8" },
	DevIconProcfile = { fg = "#a074c4" },
	DevIconProlog = { fg = "#e4b854" },
	DevIconPrusaSlicer = { fg = "#ec6b23" },
	DevIconPsManifestfile = { fg = "#6975c4" },
	DevIconPsScriptModulefile = { fg = "#6975c4" },
	DevIconPsScriptfile = { fg = "#4273ca" },
	DevIconPsb = { fg = "#519aba" },
	DevIconPsd = { fg = "#519aba" },
	DevIconPub = { fg = "#e3c58e" },
	DevIconPulseCodeModulation = { fg = "#0075aa" },
	DevIconPuppyLinux = { fg = "#a2aeb9" },
	DevIconPxd = { fg = "#5aa7e4" },
	DevIconPxi = { fg = "#5aa7e4" },
	DevIconPy = { fg = "#ffbc03" },
	["DevIconPy.typed"] = { fg = "#ffbc03" },
	DevIconPyLintConfig = { fg = "#6d8086" },
	DevIconPyc = { fg = "#ffe291" },
	DevIconPyd = { fg = "#ffe291" },
	DevIconPyi = { fg = "#ffbc03" },
	DevIconPyo = { fg = "#ffe291" },
	DevIconPyw = { fg = "#5aa7e4" },
	DevIconPyx = { fg = "#5aa7e4" },
	DevIconQt = { fg = "#40cd52" },
	DevIconQtile = { fg = "#ffffff" },
	DevIconQubesOS = { fg = "#3774d8" },
	DevIconQuery = { fg = "#90a850" },
	DevIconR = { fg = "#2266ba" },
	DevIconRake = { fg = "#701516" },
	DevIconRakefile = { fg = "#701516" },
	DevIconRar = { fg = "#eca517" },
	DevIconRasi = { fg = "#cbcb41" },
	DevIconRaspberryPiOS = { fg = "#be1848" },
	DevIconRazorPage = { fg = "#512bd4" },
	DevIconRb = { fg = "#701516" },
	DevIconReScript = { fg = "#cc3e44" },
	DevIconReScriptInterface = { fg = "#f55385" },
	DevIconReadme = { fg = "#ededed" },
	DevIconRedhat = { fg = "#ee0000" },
	DevIconRlib = { fg = "#dea584" },
	DevIconRmd = { fg = "#519aba" },
	DevIconRobotsTxt = { fg = "#5d7096" },
	DevIconRockyLinux = { fg = "#0fb37d" },
	DevIconRproj = { fg = "#358a5b" },
	DevIconRs = { fg = "#dea584" },
	DevIconRss = { fg = "#fb9d3b" },
	DevIconSRCINFO = { fg = "#0f94d2" },
	DevIconSabayon = { fg = "#c6c6c6" },
	DevIconSass = { fg = "#f55385" },
	DevIconScala = { fg = "#cc3e44" },
	DevIconScalaScript = { fg = "#cc3e44" },
	DevIconScheme = { fg = "#eeeeee" },
	DevIconScss = { fg = "#f55385" },
	DevIconSecurity = { fg = "#bec4c9" },
	DevIconSettingsJson = { fg = "#854cc7" },
	DevIconSh = { fg = "#4d5a5e" },
	DevIconSha1 = { fg = "#8c86af" },
	DevIconSha224 = { fg = "#8c86af" },
	DevIconSha256 = { fg = "#8c86af" },
	DevIconSha384 = { fg = "#8c86af" },
	DevIconSha512 = { fg = "#8c86af" },
	DevIconSharedObject = { fg = "#dcddd6" },
	DevIconSig = { fg = "#e37933" },
	DevIconSignature = { fg = "#e37933" },
	DevIconSketchUp = { fg = "#839463" },
	DevIconSlackware = { fg = "#475fa9" },
	DevIconSlim = { fg = "#e34c26" },
	DevIconSln = { fg = "#854cc7" },
	DevIconSlnx = { fg = "#854cc7" },
	DevIconSml = { fg = "#e37933" },
	DevIconSolidWorksAsm = { fg = "#839463" },
	DevIconSolidWorksPrt = { fg = "#839463" },
	DevIconSolidity = { fg = "#519aba" },
	DevIconSolus = { fg = "#4b5163" },
	DevIconSolveSpace = { fg = "#839463" },
	DevIconSpecJs = { fg = "#cbcb41" },
	DevIconSpecTs = { fg = "#519aba" },
	DevIconSql = { fg = "#dad8d8" },
	DevIconSrt = { fg = "#ffb713" },
	DevIconSsa = { fg = "#ffb713" },
	DevIconStaticLibraryArchive = { fg = "#dcddd6" },
	DevIconSte = { fg = "#839463" },
	DevIconStep = { fg = "#839463" },
	DevIconStorybookJavaScript = { fg = "#ff4785" },
	DevIconStorybookJsx = { fg = "#ff4785" },
	DevIconStorybookMjs = { fg = "#ff4785" },
	DevIconStorybookSvelte = { fg = "#ff4785" },
	DevIconStorybookTsx = { fg = "#ff4785" },
	DevIconStorybookTypeScript = { fg = "#ff4785" },
	DevIconStorybookVue = { fg = "#ff4785" },
	DevIconStp = { fg = "#839463" },
	DevIconStyl = { fg = "#8dc149" },
	DevIconSub = { fg = "#ffb713" },
	DevIconSublime = { fg = "#e37933" },
	DevIconSuo = { fg = "#854cc7" },
	DevIconSvelte = { fg = "#ff3e00" },
	DevIconSvelteConfig = { fg = "#ff3e00" },
	DevIconSvg = { fg = "#ffb13b" },
	DevIconSvgz = { fg = "#ffb13b" },
	DevIconSway = { fg = "#68751c" },
	DevIconSwift = { fg = "#e37933" },
	DevIconSystemVerilog = { fg = "#019833" },
	DevIconTFVars = { fg = "#5f43e9" },
	DevIconTSConfig = { fg = "#519aba" },
	DevIconTails = { fg = "#56347c" },
	DevIconTailwindConfig = { fg = "#20c2e3" },
	DevIconTcl = { fg = "#1e5cb3" },
	DevIconTempl = { fg = "#dbbd30" },
	DevIconTemplate = { fg = "#dbbd30" },
	DevIconTerminal = { fg = "#31b53e" },
	DevIconTerraform = { fg = "#5f43e9" },
	DevIconTestJs = { fg = "#cbcb41" },
	DevIconTestTs = { fg = "#519aba" },
	DevIconTex = { fg = "#3d6117" },
	DevIconTgz = { fg = "#eca517" },
	DevIconThunderbird = { fg = "#137be1" },
	DevIconTmux = { fg = "#14ba19" },
	DevIconToml = { fg = "#9c4221" },
	DevIconTor = { fg = "#519aba" },
	DevIconTorrent = { fg = "#44cda8" },
	DevIconTrisquelGNULinux = { fg = "#0f58b6" },
	DevIconTrueTypeFont = { fg = "#ececec" },
	DevIconTsx = { fg = "#1354bf" },
	DevIconTumbleweed = { fg = "#35b9ab" },
	DevIconTwig = { fg = "#8dc149" },
	DevIconTxt = { fg = "#89e051" },
	DevIconTxz = { fg = "#eca517" },
	DevIconTypeScript = { fg = "#519aba" },
	DevIconTypeScriptDeclaration = { fg = "#d59855" },
	DevIconTypeScriptReactSpec = { fg = "#1354bf" },
	DevIconTypeScriptReactTest = { fg = "#1354bf" },
	DevIconTypoScript = { fg = "#ff8700" },
	DevIconTypoScriptConfig = { fg = "#ff8700" },
	DevIconTypoScriptSetup = { fg = "#ff8700" },
	DevIconTypst = { fg = "#0dbcc0" },
	DevIconUI = { fg = "#015bf0" },
	DevIconUbuntu = { fg = "#dd4814" },
	DevIconVHDL = { fg = "#019833" },
	DevIconVLC = { fg = "#ee7a00" },
	DevIconVRML = { fg = "#888888" },
	DevIconVagrantfile = { fg = "#1563ff" },
	DevIconVala = { fg = "#7b3db9" },
	DevIconVanillaOS = { fg = "#fabd4d" },
	DevIconVercel = { fg = "#ffffff" },
	DevIconVerilog = { fg = "#019833" },
	DevIconVim = { fg = "#019833" },
	DevIconVimrc = { fg = "#019833" },
	DevIconVlang = { fg = "#5d87bf" },
	DevIconVoid = { fg = "#295340" },
	DevIconVsix = { fg = "#854cc7" },
	DevIconVue = { fg = "#8dc149" },
	DevIconWasm = { fg = "#5c4cdb" },
	DevIconWavPack = { fg = "#00afff" },
	DevIconWavPackCorrection = { fg = "#00afff" },
	DevIconWaveformAudioFile = { fg = "#00afff" },
	DevIconWebOpenFontFormat = { fg = "#ececec" },
	DevIconWebm = { fg = "#fd971f" },
	DevIconWebmanifest = { fg = "#f1e05a" },
	DevIconWebp = { fg = "#a074c4" },
	DevIconWebpack = { fg = "#519aba" },
	DevIconWeston = { fg = "#ffbb01" },
	DevIconWindows = { fg = "#00a4ef" },
	DevIconWindowsMediaAudio = { fg = "#00afff" },
	DevIconWindowsMediaVideo = { fg = "#fd971f" },
	DevIconWranglerConfig = { fg = "#f48120" },
	DevIconXInitrc = { fg = "#e54d18" },
	DevIconXSettingsdConf = { fg = "#e54d18" },
	DevIconXaml = { fg = "#512bd4" },
	DevIconXauthority = { fg = "#e54d18" },
	DevIconXcLocalization = { fg = "#2596be" },
	DevIconXcPlayground = { fg = "#e37933" },
	DevIconXeroLinux = { fg = "#888fe2" },
	DevIconXfce = { fg = "#00aadf" },
	DevIconXls = { fg = "#207245" },
	DevIconXlsx = { fg = "#207245" },
	DevIconXml = { fg = "#e37933" },
	DevIconXorgConf = { fg = "#e54d18" },
	DevIconXpi = { fg = "#ff1b01" },
	DevIconXresources = { fg = "#e54d18" },
	DevIconXsession = { fg = "#e54d18" },
	DevIconXul = { fg = "#e37933" },
	DevIconXz = { fg = "#eca517" },
	DevIconYaml = { fg = "#6d8086" },
	DevIconYml = { fg = "#6d8086" },
	DevIconZig = { fg = "#f69a1b" },
	DevIconZigObjectNotation = { fg = "#f69a1b" },
	DevIconZip = { fg = "#eca517" },
	DevIconZorin = { fg = "#14a1e8" },
	DevIconZsh = { fg = "#89e051" },
	DevIconZshenv = { fg = "#89e051" },
	DevIconZshprofile = { fg = "#89e051" },
	DevIconZshrc = { fg = "#89e051" },
	DevIconZst = { fg = "#eca517" },
	DevIconapk = { fg = "#34a853" },
	DevIconawesome = { fg = "#535d6c" },
	DevIconcuda = { fg = "#89e051" },
	DevIconcudah = { fg = "#a074c4" },
	DevIcondwm = { fg = "#1177aa" },
	DevIconi3 = { fg = "#e8ebee" },
	DevIconnode = { fg = "#5fa04e" },
	DevIconopenSUSE = { fg = "#6fb424" },
	DevIconpostmarketOS = { fg = "#009900" },
	DevIconriver = { fg = "#000000" },
	DevIconsbt = { fg = "#cc3e44" },
	DevIconxmonad = { fg = "#fd4d5d" },
	DiagnosticDeprecated = { sp = "nvimlightred", strikethrough = true },
	["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
	DiagnosticError = { fg = "#c53b53" },
	DiagnosticFloatingError = { link = "DiagnosticError" },
	DiagnosticSignError = { link = "DiagnosticError" },
	DiagnosticVirtualLinesError = { link = "DiagnosticError" },
	OilDelete = { link = "DiagnosticError" },
	OilOrphanLinkTarget = { link = "DiagnosticError" },
	DiagnosticHint = { fg = "#009955" },
	DiagnosticFloatingHint = { link = "DiagnosticHint" },
	DiagnosticSignHint = { link = "DiagnosticHint" },
	DiagnosticVirtualLinesHint = { link = "DiagnosticHint" },
	MiniDepsHint = { link = "DiagnosticHint" },
	OilCopy = { link = "DiagnosticHint" },
	DiagnosticInfo = { fg = "#0db9d7" },
	DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
	DiagnosticSignInfo = { link = "DiagnosticInfo" },
	DiagnosticVirtualLinesInfo = { link = "DiagnosticInfo" },
	MiniDepsInfo = { link = "DiagnosticInfo" },
	OilCreate = { link = "DiagnosticInfo" },
	DiagnosticOk = { fg = "nvimlightgreen" },
	DiagnosticFloatingOk = { link = "DiagnosticOk" },
	DiagnosticSignOk = { link = "DiagnosticOk" },
	DiagnosticVirtualLinesOk = { link = "DiagnosticOk" },
	DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
	DiagnosticUnderlineError = { sp = "#c53b53", undercurl = true },
	DiagnosticUnderlineHint = { sp = "#4fd6be", undercurl = true },
	DiagnosticUnderlineInfo = { sp = "#0db9d7", undercurl = true },
	DiagnosticUnderlineOk = { sp = "nvimlightgreen", underline = true },
	DiagnosticUnderlineWarn = { sp = "#ffc777", undercurl = true },
	DiagnosticUnnecessary = { fg = "#000000" },
	DiagnosticVirtualTextError = { fg = "#ff0000", bg = "#130707" },
	DiagnosticVirtualTextHint = { fg = "#ffba03", bg = "#25270e" },
	DiagnosticVirtualTextInfo = { fg = "#0db9d7", bg = "#203346" },
	DiagnosticVirtualTextWarn = { fg = "#ffc777", bg = "#38343d" },
	DiagnosticWarn = { fg = "#ffc777" },
	DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
	DiagnosticSignWarn = { link = "DiagnosticWarn" },
	DiagnosticVirtualLinesWarn = { link = "DiagnosticWarn" },
	MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
	OilMove = { link = "DiagnosticWarn" },
	DiffAdd = { bg = "#273849" },
	GitSignsAddLn = { link = "DiffAdd" },
	GitSignsAddPreview = { link = "DiffAdd" },
	MiniDiffOverAdd = { link = "DiffAdd" },
	TelescopeResultsDiffAdd = { link = "DiffAdd" },
	["@diff.plus"] = { link = "DiffAdd" },
	DiffChange = { bg = "#252a3f" },
	GitSignsChangeLn = { link = "DiffChange" },
	MiniDiffOverContext = { link = "DiffChange" },
	TelescopeResultsDiffChange = { link = "DiffChange" },
	["@diff.delta"] = { link = "DiffChange" },
	DiffDelete = { bg = "#3a273a" },
	GitSignsDeletePreview = { link = "DiffDelete" },
	GitSignsDeleteVirtLn = { link = "DiffDelete" },
	MiniDiffOverDelete = { link = "DiffDelete" },
	TelescopeResultsDiffDelete = { link = "DiffDelete" },
	["@diff.minus"] = { link = "DiffDelete" },
	DiffText = { bg = "#394b70" },
	MiniDiffOverChange = { link = "DiffText" },
	Directory = { fg = "#82aaff" },
	LspKindFolder = { link = "Directory" },
	MiniFilesDirectory = { link = "Directory" },
	MiniPickIconDirectory = { link = "Directory" },
	OilDir = { link = "Directory" },
	TelescopePreviewDate = { link = "Directory" },
	TelescopePreviewDirectory = { link = "Directory" },
	EndOfBuffer = { fg = "#222436" },
	Error = { fg = "#c53b53" },
	NvimInvalid = { link = "Error" },
	luaError = { link = "Error" },
	luaParenError = { link = "Error" },
	ErrorMsg = { fg = "#c53b53" },
	NvimInvalidSpacing = { link = "ErrorMsg" },
	FloatBorder = { fg = "#0f0f14", bg = "#0f0f14" },
	MiniClueBorder = { link = "FloatBorder" },
	MiniFilesBorder = { link = "FloatBorder" },
	MiniNotifyBorder = { link = "FloatBorder" },
	MiniPickBorder = { link = "FloatBorder" },
	WhichKeyBorder = { link = "FloatBorder" },
	FloatShadow = { bg = "nvimdarkgrey4", blend = 80 },
	FloatShadowThrough = { bg = "nvimdarkgrey4", blend = 100 },
	FloatTitle = { fg = "#589ed7", bg = "#1e2030" },
	FloatFooter = { link = "FloatTitle" },
	MiniClueTitle = { link = "FloatTitle" },
	MiniFilesTitle = { link = "FloatTitle" },
	MiniNotifyTitle = { link = "FloatTitle" },
	WhichKeyTitle = { link = "FloatTitle" },
	FoldColumn = { fg = "#636da6" },
	CursorLineFold = { link = "FoldColumn" },
	Folded = { fg = "#82aaff", bg = "#3b4261" },
	Foo = { fg = "#c8d3f5", bg = "#ff007c" },
	Function = { fg = "#82aaff" },
	TelescopeResultsClass = { link = "Function" },
	TelescopeResultsField = { link = "Function" },
	TelescopeResultsFunction = { link = "Function" },
	luaFunction = { link = "Function" },
	luaMetaMethod = { link = "Function" },
	["@function"] = { link = "Function" },
	["@function.method"] = { link = "Function" },
	GitSignsAdd = { fg = "#b8db87" },
	GitSignsAddCul = { link = "GitSignsAdd" },
	GitSignsAddNr = { link = "GitSignsAdd" },
	GitSignsUntracked = { link = "GitSignsAdd" },
	GitSignsChange = { fg = "#7ca1f2" },
	GitSignsChangeCul = { link = "GitSignsChange" },
	GitSignsChangeNr = { link = "GitSignsChange" },
	GitSignsChangedelete = { link = "GitSignsChange" },
	GitSignsDelete = { fg = "#e26a75" },
	GitSignsDeleteCul = { link = "GitSignsDelete" },
	GitSignsDeleteNr = { link = "GitSignsDelete" },
	GitSignsTopdelete = { link = "GitSignsDelete" },
	GitSignsStagedAdd = { fg = "#597b60" },
	GitSignsStagedAddCul = { fg = "#597b60" },
	GitSignsStagedAddLn = { fg = "#77787c", bg = "#005523" },
	GitSignsStagedAddNr = { fg = "#597b60" },
	GitSignsStagedChange = { fg = "#467c7b" },
	GitSignsStagedChangeCul = { fg = "#467c7b" },
	GitSignsStagedChangeLn = { fg = "#77787c", bg = "#4f5258" },
	GitSignsStagedChangeNr = { fg = "#467c7b" },
	GitSignsStagedChangedelete = { fg = "#467c7b" },
	GitSignsStagedChangedeleteCul = { fg = "#467c7b" },
	GitSignsStagedChangedeleteLn = { fg = "#77787c", bg = "#4f5258" },
	GitSignsStagedChangedeleteNr = { fg = "#467c7b" },
	GitSignsStagedDelete = { fg = "#7f605c" },
	GitSignsStagedDeleteCul = { fg = "#7f605c" },
	GitSignsStagedDeleteNr = { fg = "#7f605c" },
	GitSignsStagedTopdelete = { fg = "#7f605c" },
	GitSignsStagedTopdeleteCul = { fg = "#7f605c" },
	GitSignsStagedTopdeleteNr = { fg = "#7f605c" },
	GitSignsStagedUntracked = { fg = "#597b60" },
	GitSignsStagedUntrackedCul = { fg = "#597b60" },
	GitSignsStagedUntrackedLn = { fg = "#77787c", bg = "#005523" },
	GitSignsStagedUntrackedNr = { fg = "#597b60" },
	Identifier = { fg = "#c099ff" },
	NvimIdentifier = { link = "Identifier" },
	TelescopeMultiIcon = { link = "Identifier" },
	TelescopeResultsIdentifier = { link = "Identifier" },
	luaFunc = { link = "Identifier" },
	["@markup.link.label.symbol"] = { link = "Identifier" },
	IncSearch = { fg = "#1b1d2b", bg = "#ff966c" },
	CurSearch = { link = "IncSearch" },
	MiniOperatorsExchangeFrom = { link = "IncSearch" },
	MiniPickPreviewRegion = { link = "IncSearch" },
	Italic = { fg = "#c8d3f5", italic = true },
	Keyword = { fg = "#86e1fc" },
	OilSocket = { link = "Keyword" },
	TelescopePreviewSticky = { link = "Keyword" },
	LazyProgressDone = { fg = "#ff007c", bold = true },
	LazyProgressTodo = { fg = "#3b4261", bold = true },
	LineNr = { fg = "#3b4261" },
	TelescopeResultsLineNr = { link = "LineNr" },
	LineNrAbove = { fg = "#017dc5" },
	LineNrBelow = { fg = "#017dc5" },
	LspCodeLens = { fg = "#636da6" },
	LspCodeLensSeparator = { link = "LspCodeLens" },
	LspInfoBorder = { fg = "#589ed7", bg = "#1e2030" },
	LspInlayHint = { fg = "#3d4267" },
	LspReferenceRead = { bg = "#3b4261" },
	LspReferenceText = { bg = "#3b4261" },
	LspReferenceTarget = { link = "LspReferenceText" },
	LspReferenceWrite = { bg = "#3b4261" },
	LspSignatureActiveParameter = { bg = "#262f50", bold = true },
	BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
	MatchParen = { fg = "#ff966c", bold = true },
	MiniAnimateCursor = { nocombine = true, reverse = true },
	MiniCompletionActiveParameter = { underline = true },
	MiniCursorword = { bg = "#3b4261" },
	MiniCursorwordCurrent = { bg = "#3b4261" },
	MiniDepsTitleError = { fg = "#1b1d2b", bg = "#e26a75" },
	MiniDepsTitleUpdate = { fg = "#1b1d2b", bg = "#b8db87" },
	MiniDiffSignAdd = { fg = "#b8db87" },
	MiniDiffSignChange = { fg = "#7ca1f2" },
	MiniDiffSignDelete = { fg = "#e26a75" },
	MiniFilesFile = { fg = "#c8d3f5" },
	MiniFilesTitleFocused = { fg = "#589ed7", bg = "#1e2030", bold = true },
	MiniHipatternsFixme = { fg = "#1b1d2b", bg = "#c53b53", bold = true },
	MiniHipatternsHack = { fg = "#1b1d2b", bg = "#ffc777", bold = true },
	MiniHipatternsNote = { fg = "#1b1d2b", bg = "#4fd6be", bold = true },
	MiniHipatternsTodo = { fg = "#1b1d2b", bg = "#0db9d7", bold = true },
	MiniIconsAzure = { fg = "#0db9d7" },
	WhichKeyIconAzure = { link = "MiniIconsAzure" },
	MiniIconsBlue = { fg = "#82aaff" },
	WhichKeyIconBlue = { link = "MiniIconsBlue" },
	MiniIconsCyan = { fg = "#4fd6be" },
	WhichKeyIconCyan = { link = "MiniIconsCyan" },
	MiniIconsGreen = { fg = "#c3e88d" },
	WhichKeyIconGreen = { link = "MiniIconsGreen" },
	MiniIconsGrey = { fg = "#c8d3f5" },
	WhichKeyIconGrey = { link = "MiniIconsGrey" },
	MiniIconsOrange = { fg = "#ff966c" },
	WhichKeyIconOrange = { link = "MiniIconsOrange" },
	MiniIconsPurple = { fg = "#fca7ea" },
	WhichKeyIconPurple = { link = "MiniIconsPurple" },
	MiniIconsRed = { fg = "#ff757f" },
	WhichKeyIconRed = { link = "MiniIconsRed" },
	MiniIconsYellow = { fg = "#ffc777" },
	WhichKeyIconYellow = { link = "MiniIconsYellow" },
	MiniIndentscopePrefix = { nocombine = true },
	MiniIndentscopeSymbol = { fg = "#65bcff", nocombine = true },
	MiniJump = { fg = "#ffffff", bg = "#ff007c" },
	MiniJump2dSpot = { fg = "#ff007c", bold = true, nocombine = true },
	MiniJump2dSpotAhead = { fg = "#4fd6be", bg = "#1e2030", nocombine = true },
	MiniJump2dSpotUnique = { fg = "#ff966c", bold = true, nocombine = true },
	MiniPickBorderText = { fg = "#4fd6be", bg = "#1e2030" },
	MiniPickPrompt = { fg = "#0db9d7", bg = "#1e2030" },
	MiniStarterCurrent = { nocombine = true },
	MiniStarterFooter = { fg = "#ffc777", italic = true },
	MiniStarterHeader = { fg = "#82aaff" },
	MiniStarterInactive = { fg = "#636da6", italic = true },
	MiniStarterItem = { fg = "#c8d3f5" },
	MiniStarterItemBullet = { fg = "#589ed7" },
	MiniStarterItemPrefix = { fg = "#ffc777" },
	MiniStarterQuery = { fg = "#0db9d7" },
	MiniStarterSection = { fg = "#65bcff" },
	MiniStatuslineDevinfo = { fg = "#828bb8", bg = "#3b4261" },
	MiniStatuslineFileinfo = { fg = "#828bb8", bg = "#3b4261" },
	MiniStatuslineFilename = { fg = "#828bb8", bg = "#2f334d" },
	MiniStatuslineInactive = { fg = "#82aaff", bg = "#1e2030" },
	MiniStatuslineModeCommand = { fg = "#1b1d2b", bg = "#ffc777", bold = true },
	MiniStatuslineModeInsert = { fg = "#1b1d2b", bg = "#c3e88d", bold = true },
	MiniStatuslineModeNormal = { fg = "#1b1d2b", bg = "#82aaff", bold = true },
	MiniStatuslineModeOther = { fg = "#1b1d2b", bg = "#4fd6be", bold = true },
	MiniStatuslineModeReplace = { fg = "#1b1d2b", bg = "#ff757f", bold = true },
	MiniStatuslineModeVisual = { fg = "#1b1d2b", bg = "#c099ff", bold = true },
	MiniSurround = { fg = "#1b1d2b", bg = "#ff966c" },
	MiniTablineCurrent = { fg = "#c8d3f5", bg = "#3b4261" },
	MiniTablineFill = { bg = "#1b1d2b" },
	MiniTablineHidden = { fg = "#737aa2", bg = "#1e2030" },
	MiniTablineModifiedCurrent = { fg = "#ffc777", bg = "#3b4261" },
	MiniTablineModifiedHidden = { fg = "#bd9664", bg = "#1e2030" },
	MiniTablineModifiedVisible = { fg = "#ffc777", bg = "#1e2030" },
	MiniTablineTabpagesection = { bg = "#3b4261" },
	MiniTablineVisible = { fg = "#c8d3f5", bg = "#1e2030" },
	MiniTestEmphasis = { bold = true },
	MiniTestFail = { fg = "#ff757f", bold = true },
	MiniTestPass = { fg = "#c3e88d", bold = true },
	MiniTrailspace = { bg = "#ff757f" },
	ModeMsg = { fg = "#828bb8", bold = true },
	MoreMsg = { fg = "#82aaff" },
	MsgArea = { fg = "#828bb8" },
	NonText = { fg = "#545c7e" },
	GitSignsCurrentLineBlame = { link = "NonText" },
	TelescopePreviewHyphen = { link = "NonText" },
	TelescopePromptCounter = { link = "NonText" },
	TelescopeResultsDiffUntracked = { link = "NonText" },
	NormalFloat = { fg = "#a0c0d0", bg = "#0f0f14" },
	BlinkCmpDocSeparator = { link = "NormalFloat" },
	MiniAnimateNormalFloat = { link = "NormalFloat" },
	MiniClueDescSingle = { link = "NormalFloat" },
	MiniFilesNormal = { link = "NormalFloat" },
	MiniMapNormal = { link = "NormalFloat" },
	MiniNotifyNormal = { link = "NormalFloat" },
	MiniPickNormal = { link = "NormalFloat" },
	NormalNC = { fg = "#c8d3f5" },
	NormalSB = { fg = "#828bb8", bg = "#1e2030" },
	NvimInternalError = { fg = "red", bg = "red" },
	NvimFigureBrace = { link = "NvimInternalError" },
	NvimInvalidSingleQuotedUnknownEscape = { link = "NvimInternalError" },
	NvimSingleQuotedUnknownEscape = { link = "NvimInternalError" },
	Operator = { fg = "#89ddff" },
	NvimAssignment = { link = "Operator" },
	NvimOperator = { link = "Operator" },
	TelescopeResultsOperator = { link = "Operator" },
	luaOperator = { link = "Operator" },
	PHerror = { fg = "#dc2626" },
	PHinfo = { fg = "#4fc1ff" },
	PHwarning = { fg = "#fbbf24" },
	Pmenu = { fg = "#c8d3f5", bg = "#1e2030" },
	PmenuExtra = { link = "Pmenu" },
	PmenuKind = { link = "Pmenu" },
	PmenuMatch = { fg = "#65bcff", bg = "#1e2030" },
	PmenuMatchSel = { fg = "#65bcff", bg = "#363c58" },
	PmenuSbar = { bg = "#27293a" },
	BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
	PmenuSel = { bg = "#363c58" },
	BlinkCmpMenuSelection = { link = "PmenuSel" },
	PmenuExtraSel = { link = "PmenuSel" },
	PmenuKindSel = { link = "PmenuSel" },
	PmenuThumb = { bg = "#3b4261" },
	BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
	PreProc = { fg = "#86e1fc" },
	Define = { link = "PreProc" },
	Include = { link = "PreProc" },
	Macro = { link = "PreProc" },
	PreCondit = { link = "PreProc" },
	["@annotation"] = { link = "PreProc" },
	["@attribute"] = { link = "PreProc" },
	["@keyword.directive"] = { link = "PreProc" },
	Question = { fg = "#82aaff" },
	QuickFixLine = { bg = "#2d3f76", bold = true },
	RedrawDebugClear = { bg = "nvimdarkyellow" },
	RedrawDebugComposed = { bg = "nvimdarkgreen" },
	RedrawDebugNormal = { reverse = true },
	RedrawDebugRecompose = { bg = "nvimdarkred" },
	Removed = { fg = "nvimlightred" },
	Search = { fg = "#c8d3f5", bg = "#3e68d7" },
	TelescopePreviewMatch = { link = "Search" },
	SignColumn = { fg = "#3b4261" },
	CursorLineSign = { link = "SignColumn" },
	SignColumnSB = { fg = "#3b4261", bg = "#1e2030" },
	Special = { fg = "#65bcff" },
	Delimiter = { link = "Special" },
	LspKindColor = { link = "Special" },
	LspKindEvent = { link = "Special" },
	MiniMapSymbolCount = { link = "Special" },
	OilChange = { link = "Special" },
	SpecialChar = { link = "Special" },
	SpecialComment = { link = "Special" },
	Tag = { link = "Special" },
	TelescopePreviewLink = { link = "Special" },
	["@attribute.builtin"] = { link = "Special" },
	["@constant.builtin"] = { link = "Special" },
	["@function.builtin"] = { link = "Special" },
	["@markup.math"] = { link = "Special" },
	["@tag.builtin"] = { link = "Special" },
	SpecialKey = { fg = "#545c7e" },
	SpellBad = { sp = "#c53b53", undercurl = true },
	SpellCap = { sp = "#ffc777", undercurl = true },
	SpellLocal = { sp = "#0db9d7", undercurl = true },
	SpellRare = { sp = "#4fd6be", undercurl = true },
	Statement = { fg = "#c099ff" },
	Conditional = { link = "Statement" },
	Exception = { link = "Statement" },
	Label = { link = "Statement" },
	Repeat = { link = "Statement" },
	TelescopePreviewSocket = { link = "Statement" },
	TelescopePreviewWrite = { link = "Statement" },
	luaStatement = { link = "Statement" },
	StatusLine = { fg = "#828bb8", bg = "#1e2030" },
	MsgSeparator = { link = "StatusLine" },
	StatusLineTerm = { link = "StatusLine" },
	WinBar = { link = "StatusLine" },
	StatusLineNC = { fg = "#3b4261", bg = "#1e2030" },
	StatusLineTermNC = { link = "StatusLineNC" },
	WinBarNC = { link = "StatusLineNC" },
	String = { fg = "#c3e88d" },
	NvimString = { link = "String" },
	TelescopePreviewExecute = { link = "String" },
	TelescopePreviewSize = { link = "String" },
	luaString = { link = "String" },
	luaString2 = { link = "String" },
	["@markup.raw"] = { link = "String" },
	["@string"] = { link = "String" },
	Substitute = { fg = "#1b1d2b", bg = "#ff757f" },
	SupermavenSuggestion = { fg = "#444a73" },
	TabLine = { fg = "#3b4261", bg = "#1e2030" },
	TabLineFill = { bg = "#1b1d2b" },
	TabLineSel = { fg = "#1b1d2b", bg = "#82aaff" },
	TelescopeBorder = { fg = "#589ed7", bg = "#1e2030" },
	TelescopeTitle = { link = "TelescopeBorder" },
	TelescopeMatching = { fg = "#c586c0", bold = true },
	TelescopeNormal = { fg = "#c8d3f5", bg = "#1e2030" },
	TelescopePreviewBorder = { fg = "#1a1a22", bg = "#1a1a22" },
	TelescopePreviewNormal = { fg = "#a0c0d0", bg = "#1a1a22" },
	TelescopePreviewMessage = { link = "TelescopePreviewNormal" },
	TelescopePromptBorder = { fg = "#1a1a22", bg = "#1a1a22" },
	TelescopePromptNormal = { fg = "#ffffff", bg = "#1a1a22" },
	TelescopePromptPrefix = { fg = "#c586c0", bold = true },
	TelescopeResultsBorder = { fg = "#05050a", bg = "#05050a" },
	TelescopeResultsComment = { fg = "#545c7e" },
	TelescopeResultsNormal = { fg = "#a0c0d0", bg = "#05050a" },
	TelescopeSelection = { fg = "#ffffff", bg = "#252530" },
	TelescopeSelectionCaret = { link = "TelescopeSelection" },
	TermCursor = { reverse = true },
	GitSignsAddInline = { link = "TermCursor" },
	GitSignsChangeInline = { link = "TermCursor" },
	GitSignsDeleteInline = { link = "TermCursor" },
	Title = { fg = "#82aaff", bold = true },
	MiniDepsTitle = { link = "Title" },
	MiniMapSymbolLine = { link = "Title" },
	["@markup.heading"] = { link = "Title" },
	Todo = { fg = "#222436", bg = "#ffc777" },
	luaTodo = { link = "Todo" },
	TodoBgFIX = { fg = "#000000", bg = "#c53b53", bold = true },
	TodoBgHACK = { fg = "#000000", bg = "#ffc777", bold = true },
	TodoBgNOTE = { fg = "#000000", bg = "#009955", bold = true },
	TodoBgPERF = { fg = "#000000", bg = "#c099ff", bold = true },
	TodoBgTEST = { fg = "#000000", bg = "#c099ff", bold = true },
	TodoBgTODO = { fg = "#000000", bg = "#0db9d7", bold = true },
	TodoBgWARN = { fg = "#000000", bg = "#ffc777", bold = true },
	TodoFgFIX = { fg = "#c53b53" },
	TodoFgHACK = { fg = "#ffc777" },
	TodoFgNOTE = { fg = "#009955" },
	TodoFgPERF = { fg = "#c099ff" },
	TodoFgTEST = { fg = "#c099ff" },
	TodoFgTODO = { fg = "#0db9d7" },
	TodoFgWARN = { fg = "#ffc777" },
	TodoSignFIX = { fg = "#c53b53" },
	TodoSignHACK = { fg = "#ffc777" },
	TodoSignNOTE = { fg = "#009955" },
	TodoSignPERF = { fg = "#c099ff" },
	TodoSignTEST = { fg = "#c099ff" },
	TodoSignTODO = { fg = "#0db9d7" },
	TodoSignWARN = { fg = "#ffc777" },
	Type = { fg = "#65bcff" },
	NvimNumberPrefix = { link = "Type" },
	NvimOptionSigil = { link = "Type" },
	StorageClass = { link = "Type" },
	Structure = { link = "Type" },
	TelescopeMultiSelection = { link = "Type" },
	Typedef = { link = "Type" },
	["@markup.environment.name"] = { link = "Type" },
	["@type"] = { link = "Type" },
	Underlined = { underline = true },
	["@markup.link.url"] = { link = "Underlined" },
	["@string.special.url"] = { link = "Underlined" },
	VertSplit = { fg = "#1b1d2b" },
	Visual = { bg = "#2d3f76" },
	BlinkCmpDocCursorLine = { link = "Visual" },
	MiniPickMatchMarked = { link = "Visual" },
	SnippetTabstop = { link = "Visual" },
	TelescopePreviewLine = { link = "Visual" },
	VisualNOS = { bg = "#2d3f76" },
	WarningMsg = { fg = "#ffc777" },
	WhichKey = { fg = "#86e1fc" },
	WhichKeyDesc = { fg = "#c099ff" },
	WhichKeyGroup = { fg = "#82aaff" },
	WhichKeyNormal = { bg = "#1e2030" },
	WhichKeySeparator = { fg = "#636da6" },
	WhichKeyValue = { fg = "#737aa2" },
	Whitespace = { fg = "#3b4261" },
	WildMenu = { bg = "#2d3f76" },
	WinSeparator = { fg = "#1b1d2b", bold = true },
	debugBreakpoint = { fg = "#0db9d7", bg = "#203346" },
	debugPC = { bg = "#1e2030" },
	diffAdded = { fg = "#b8db87", bg = "#273849" },
	MiniDepsChangeAdded = { link = "diffAdded" },
	diffChanged = { fg = "#7ca1f2", bg = "#252a3f" },
	diffFile = { fg = "#82aaff" },
	diffIndexLine = { fg = "#c099ff" },
	diffLine = { fg = "#636da6" },
	diffNewFile = { fg = "#65bcff", bg = "#273849" },
	diffOldFile = { fg = "#65bcff", bg = "#3a273a" },
	diffRemoved = { fg = "#e26a75", bg = "#3a273a" },
	MiniDepsChangeRemoved = { link = "diffRemoved" },
	healthError = { fg = "#c53b53" },
	healthSuccess = { fg = "#4fd6be" },
	healthWarning = { fg = "#ffc777" },
	helpCommand = { fg = "#82aaff", bg = "#444a73" },
	helpExample = { fg = "#636da6" },
	htmlH1 = { fg = "#c099ff", bold = true },
	htmlH2 = { fg = "#82aaff", bold = true },
	lCursor = { fg = "#222436", bg = "#c8d3f5" },
	["lualine_a_command"] = { fg = "#112638", bg = "#ffda7b", bold = true, nocombine = true },
	["lualine_a_inactive"] = { fg = "#6c6f93", bg = "#2c3043", bold = true, nocombine = true },
	["lualine_a_insert"] = { fg = "#112638", bg = "#76ff03", bold = true, nocombine = true },
	["lualine_a_normal"] = { fg = "#112638", bg = "#2979ff", bold = true, nocombine = true },
	["lualine_a_replace"] = { fg = "#112638", bg = "#ff1744", bold = true, nocombine = true },
	["lualine_a_visual"] = { fg = "#112638", bg = "#ff61ef", bold = true, nocombine = true },
	["lualine_b_command"] = { fg = "#112638", bg = "#76ff03", nocombine = true },
	["lualine_b_inactive"] = { fg = "#112638", bg = "#76ff03", nocombine = true },
	["lualine_b_insert"] = { fg = "#112638", bg = "#9abbe6", nocombine = true },
	["lualine_b_normal"] = { fg = "#112638", bg = "#9abbe6", nocombine = true },
	["lualine_b_replace"] = { fg = "#112638", bg = "#76ff03", nocombine = true },
	["lualine_b_visual"] = { fg = "#112638", bg = "#76ff03", nocombine = true },
	["lualine_c_command"] = { fg = "#c3ccdc", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_command"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_inactive"] = { fg = "#c53b53", bg = "#2c3043", nocombine = true },
	["lualine_c_diagnostics_error_insert"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_normal"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_replace"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_terminal"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_error_visual"] = { fg = "#c53b53", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_command"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_inactive"] = { fg = "#009955", bg = "#2c3043", nocombine = true },
	["lualine_c_diagnostics_hint_insert"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_normal"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_replace"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_terminal"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_hint_visual"] = { fg = "#009955", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_command"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_inactive"] = { fg = "#0db9d7", bg = "#2c3043", nocombine = true },
	["lualine_c_diagnostics_info_insert"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_normal"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_replace"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_terminal"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_info_visual"] = { fg = "#0db9d7", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_command"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_inactive"] = { fg = "#ffc777", bg = "#2c3043", nocombine = true },
	["lualine_c_diagnostics_warn_insert"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_normal"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_replace"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_terminal"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diagnostics_warn_visual"] = { fg = "#ffc777", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_command"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_inactive"] = { fg = "#b8db87", bg = "#2c3043", nocombine = true },
	["lualine_c_diff_added_insert"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_normal"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_replace"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_terminal"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_added_visual"] = { fg = "#b8db87", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_command"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_inactive"] = { fg = "#7ca1f2", bg = "#2c3043", nocombine = true },
	["lualine_c_diff_modified_insert"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_normal"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_replace"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_terminal"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_modified_visual"] = { fg = "#7ca1f2", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_command"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_inactive"] = { fg = "#e26a75", bg = "#2c3043", nocombine = true },
	["lualine_c_diff_removed_insert"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_normal"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_replace"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_terminal"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_diff_removed_visual"] = { fg = "#e26a75", bg = "#112638", nocombine = true },
	["lualine_c_inactive"] = { fg = "#6c6f93", bg = "#2c3043", nocombine = true },
	["lualine_c_insert"] = { fg = "#c3ccdc", bg = "#112638", nocombine = true },
	["lualine_c_normal"] = { fg = "#c3ccdc", bg = "#112638", nocombine = true },
	["lualine_c_replace"] = { fg = "#c3ccdc", bg = "#112638", nocombine = true },
	["lualine_c_visual"] = { fg = "#c3ccdc", bg = "#112638", nocombine = true },
	["lualine_transitional_lualine_a_command_to_lualine_b_command"] = {
		fg = "#ffda7b",
		bg = "#76ff03",
		nocombine = true,
	},
	["lualine_transitional_lualine_a_normal_to_lualine_b_normal"] = { fg = "#2979ff", bg = "#9abbe6", nocombine = true },
	["lualine_transitional_lualine_b_command_to_lualine_c_command"] = {
		fg = "#76ff03",
		bg = "#112638",
		nocombine = true,
	},
	["lualine_transitional_lualine_b_normal_to_lualine_c_normal"] = { fg = "#9abbe6", bg = "#112638", nocombine = true },
	["lualine_transparent"] = { fg = "#c8d3f5", nocombine = true },
	["lualine_x_filetype_DevIconDefault_command"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconDefault_inactive"] = { fg = "#6d8086", bg = "#2c3043", nocombine = true },
	["lualine_x_filetype_DevIconDefault_insert"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconDefault_normal"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconDefault_replace"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconDefault_terminal"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconDefault_visual"] = { fg = "#6d8086", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_command"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_inactive"] = { fg = "#51a0cf", bg = "#2c3043", nocombine = true },
	["lualine_x_filetype_DevIconLua_insert"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_normal"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_replace"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_terminal"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	["lualine_x_filetype_DevIconLua_visual"] = { fg = "#51a0cf", bg = "#112638", nocombine = true },
	qfFileName = { fg = "#82aaff" },
	qfLineNr = { fg = "#737aa2" },
	["@comment.error"] = { fg = "#c53b53" },
	["@comment.hint"] = { fg = "#4fd6be" },
	["@comment.info"] = { fg = "#0db9d7" },
	["@comment.note"] = { fg = "#4fd6be" },
	["@comment.todo"] = { fg = "#82aaff" },
	["@comment.warning"] = { fg = "#ffc777" },
	["@constructor"] = { fg = "#c099ff" },
	["@constructor.tsx"] = { fg = "#65bcff" },
	LspKindConstructor = { link = "@constructor" },
	["@keyword"] = { fg = "#fca7ea" },
	["@keyword.function"] = { fg = "#c099ff" },
	["@keyword.coroutine"] = { link = "@keyword" },
	["@keyword.return"] = { link = "@keyword" },
	["@lsp.type.keyword"] = { link = "@keyword" },
	["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
	["@type.qualifier"] = { link = "@keyword" },
	["@label"] = { fg = "#82aaff" },
	["@lsp.type.interface"] = { fg = "#83c3fc" },
	LspKindInterface = { link = "@lsp.type.interface" },
	["@lsp.type.unresolvedReference"] = { sp = "#c53b53", undercurl = true },
	["@lsp.typemod.type.defaultLibrary"] = { fg = "#589ed7" },
	["@lsp.typemod.typeAlias.defaultLibrary"] = { fg = "#589ed7" },
	["@markup.emphasis"] = { italic = true },
	["@markup.heading.1.delimiter.vimdoc"] = { fg = "#4fd6be" },
	["@markup.heading.1.markdown"] = { fg = "#82aaff", bold = true },
	["@markup.heading.2.delimiter.vimdoc"] = { fg = "#4fd6be" },
	["@markup.heading.2.markdown"] = { fg = "#ffc777", bold = true },
	["@markup.heading.3.markdown"] = { fg = "#c3e88d", bold = true },
	["@markup.heading.4.markdown"] = { fg = "#4fd6be", bold = true },
	["@markup.heading.5.markdown"] = { fg = "#c099ff", bold = true },
	["@markup.heading.6.markdown"] = { fg = "#fca7ea", bold = true },
	["@markup.heading.7.markdown"] = { fg = "#ff966c", bold = true },
	["@markup.heading.8.markdown"] = { fg = "#ff757f", bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.link"] = { fg = "#4fd6be" },
	LspKindReference = { link = "@markup.link" },
	WhichKeyIcon = { link = "@markup.link" },
	["@markup.list"] = { fg = "#89ddff" },
	["@markup.list.checked"] = { fg = "#4fd6be" },
	["@markup.list.markdown"] = { fg = "#ff966c", bold = true },
	["@markup.list.unchecked"] = { fg = "#82aaff" },
	["@lsp.type.formatSpecifier"] = { link = "@markup.list" },
	["@markup.raw.markdown_inline"] = { fg = "#82aaff", bg = "#444a73" },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.strong"] = { bold = true },
	["@markup.underline"] = { underline = true },
	["@module"] = { fg = "#00ff9c" },
	["@module.builtin"] = { fg = "#ff757f" },
	LspKindModule = { link = "@module" },
	LspKindNamespace = { link = "@module" },
	LspKindPackage = { link = "@module" },
	["@lsp.type.namespace"] = { link = "@module" },
	["@operator"] = { fg = "#89ddff" },
	LspKindOperator = { link = "@operator" },
	["@keyword.operator"] = { link = "@operator" },
	["@lsp.type.operator"] = { link = "@operator" },
	["@lsp.typemod.operator.injected"] = { link = "@operator" },
	["@property"] = { fg = "#4fd6be" },
	LspKindProperty = { link = "@property" },
	dosIniLabel = { link = "@property" },
	["@lsp.type.property"] = { link = "@property" },
	["@tag.attribute"] = { link = "@property" },
	["@punctuation.bracket"] = { fg = "#f3c623" },
	LspKindArray = { link = "@punctuation.bracket" },
	["@punctuation.delimiter"] = { fg = "#89ddff" },
	["@punctuation.special"] = { fg = "#89ddff" },
	["@punctuation.special.markdown"] = { fg = "#ff966c" },
	["@string.documentation"] = { fg = "#ffc777" },
	["@string.escape"] = { fg = "#c099ff" },
	["@lsp.type.escapeSequence"] = { link = "@string.escape" },
	["@string.regexp"] = { fg = "#b4f9f8" },
	["@lsp.type.regexp"] = { link = "@string.regexp" },
	["@tag.delimiter.tsx"] = { fg = "#6582c3" },
	["@tag.javascript"] = { fg = "#ff757f" },
	["@tag.tsx"] = { fg = "#ff757f" },
	["@type.builtin"] = { fg = "#589ed7" },
	["@lsp.type.builtinType"] = { link = "@type.builtin" },
	["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
	["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
	["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
	["@variable"] = { fg = "#c8d3f5" },
	["@variable.builtin"] = { fg = "#ff757f" },
	["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
	["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
	["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
	["@namespace.builtin"] = { link = "@variable.builtin" },
	["@variable.member"] = { fg = "#4fd6be" },
	LspKindField = { link = "@variable.member" },
	LspKindKey = { link = "@variable.member" },
	["@variable.parameter"] = { fg = "#ffc777" },
	["@variable.parameter.builtin"] = { fg = "#f4c990" },
	["@lsp.type.parameter"] = { link = "@variable.parameter" },
	LspKindVariable = { link = "@variable" },
	["@lsp.type.generic"] = { link = "@variable" },
	["@lsp.type.namespace.python"] = { link = "@variable" },
	["@lsp.typemod.variable.injected"] = { link = "@variable" },
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
